### ISSUE TITLE
Add an option to download and keep track of Firefox Focus instead/as well.

### ISSUE THREAD

**Issue by yhoyhoj** [Tobi823/ffupdater#1]
Firefox Focus can be interesting to have as well as Firefox.
Most of the code could be reused to add this feature.
The current release directory is [https://archive.mozilla.org/pub/android/focus/latest/](https://archive.mozilla.org/pub/android/focus/latest/)

**Comment by Tobi823** [comment]
I also think that adding Firefox Focus (Firefox Klar in Germany, Austria and Switzerland) is a good idea.

Sadly https://archive.mozilla.org/pub/android/focus/latest/ doesn't have the current version (the latest release https://play.google.com/store/apps/details?id=org.mozilla.klar is from 17. July 2019) - we have to use the Github API (https://api.github.com/repos/mozilla-mobile/focus-android/releases) to check for the latest release from https://github.com/mozilla-mobile/focus-android/releases. I can do it - its no big deal.

But I've got no real idea to add this feature to the app without ruining the UI. Can you help me with the layout? 

My first idea was introducing tabs for switching between the view for the "normal" Firefox and the Klar/Focus Firefox. But I think its not pretty enought. What do you think? My sketch:

![2019_06_25_21_13_24_Android_Emulator_Pixel_2_API_28_5554](https://user-images.githubusercontent.com/10066140/60127958-cd2f6c00-9791-11e9-93bf-1d69b455edb2.png)

**Comment by dannycolin** [comment]
Talking about Focus and the GitHub API, would it be possible to also add Firefox Preview to the list?

(see: https://github.com/mozilla-mobile/fenix/releases)

**Comment by Tobi823** [comment]
Yes, it is possible. Github offers an API for quering the latest releases - for mozilla-mobile/fenix it is: 

https://api.github.com/repos/mozilla-mobile/fenix/releases/latest

But I may be difficult to detect if the local installed Preview is really the latest app version.

I will look into it in the next weeks (sry, but the next two weeks I dont have time)

**Comment by Tobi823** [comment]
I'm going to change the UI.

The current work-in-progress-state:
https://notabug.org/attachments/652ff586-434c-4cd8-95ee-a79f6d4e2f9f

What do you think? Good enought?

**Comment by dannycolin** [comment]
> But I may be difficult to detect if the local installed Preview is really the latest app version.

Shouldn't it be mostly the same code as what you use at the moment? I mean you can get Fenix version with `packageInfo` and compare it with the version returned by GitHub API.

You could use "https://api.github.com/repos/mozilla-mobile/fenix/releases" (without latest) to get an array of all the releases and pick the newest one that has `prerelease` set to `false`.

> I will look into it in the next weeks (sry, but the next two weeks I dont have time)

No rush and no need to apologies. It 's already really nice of you to make that app ;).

> What do you think? Good enought?

Looks good to me. I guess the green download button is to download/update all?

**Comment by Tobi823** [comment]
its now implemented. i'm going to release the new version in the next days.
