### ISSUE TITLE
Firefox Nightly update failed

### ISSUE THREAD

**Issue by rantpalas** [Tobi823/ffupdater#10]
Hi Tobi,

I am trying to update to the latest nightly, but I am getting an error regarding mismatched certificates.
Are you aware of any changes from Firefox?
![IMG_20200804_153625](https://user-images.githubusercontent.com/60635362/89294516-4ae9ca80-d668-11ea-82f9-647792c50830.jpg)

**Comment by Tobi823** [comment]
Thanks for the info.

FFUpdater uses the wrong API for downloading the APK files: Instead of downloading Fenix Release (5004...), FFUpdater downloads Fenix Nightly (77ea...)

I'll fix this today or tomorrow.

**Comment by Tobi823** [comment]
I've fixed the issue and initiated the release of version 69.0.0 on F-Droid (this takes some days)

Feel free to reopen the ticket if the bug is still present in 69.0.0
