### ISSUE TITLE
Remove "Styx" from FFUpdater

### ISSUE THREAD

**Issue by Tobi823** [Tobi823/ffupdater#101]
It seems that @jamal2362 does not maintain the Styx browser any longer:

- The GitHub repository (https://github.com/jamal2362/Styx) is deleted or private.
- Styx is removed from Google Play (https://play.google.com/store/apps/details?id=com.jamal2367.styx).

Due to the deleted GitHub repository, Styx cannot be downloaded by FFUpdater.
And even if - end users should not use a browser that is no longer updated.

Thanks for your work @jamal2362.

**Comment by chrislogan-foss** [comment]
Rest in piece. 🪦

**Comment by Tobi823** [comment]
Styx is now removed in version 75.0.0

**Comment by jamal2362** [comment]
Hi ✌️
Sorry for the premature end of Styx. 
But in the future the Styx browser will appear again.

Currently styx is migrated to Fulguris base. When this is completed then Styx will return as well as in the Play Store.

**Comment by Tobi823** [comment]
Thanks for the information. No problem.

I will add Styx again when the migration is completed.

**Comment by jamal2362** [comment]
No Problem. 
Thank you very much.
I will let you know if this is the case.
