### ISSUE TITLE
No network connection

### ISSUE THREAD

**Issue by Openfisi** [Tobi823/ffupdater#120]
It tells me every time I want to update or install something that I don't don't have a network connection. I do have one though and it also works fine otherwise I wouldn't be able to publish this text.

(I'm using Android 10)

![Screenshot_2022-03-20-01-41-29-450_de.marmaro.krt.ffupdater.jpg](https://user-images.githubusercontent.com/66037413/159143379-f84bf1f3-6307-4e26-adc4-62ca1cc54d0b.jpg)

**Comment by Tobi823** [comment]
I will look into this next month.

**Comment by Openfisi** [comment]
thy 💟

but any how the error is disappeared maybe 2 or 3 days ago.
I don't know if it is an error in the app or if it was an error in Android.
But since the time-span of these 3 days I have not changed anything manually.

**Comment by Tobi823** [comment]
I improved the code in version 75.2.0 - should be more stable now.
