### ISSUE TITLE
Unsupported device 

### ISSUE THREAD

**Issue by rahrah** [Tobi823/ffupdater#126]
Hi,

ffupdater 75.2.0 and 75.1.0 prevent downloads, giving the error box:

```
Unsupported device
The selected browser is incompatible with your smartphone's
processor.  Please select a different browser.

```
The problem can be fixed by rolling back to version 75.0.2.

I'm using LineageOs on a Motorola G7 Plus (no gapps microg etc).
Verified on two G7 Plus phones running LineageOS.

All browsers work find on the phones.

Might this be related to changes made in commit:

04549e34cc5cbc7ca18b0601f9229c0d1dc893c4

on 08apr22?

Thank you for your work on ffupdater.

===Rich

**Comment by David-Else** [comment]
This happens to me too.

**Comment by Tobi823** [comment]
I can reproduce the bug. Fixing should be simple

**Comment by Tobi823** [comment]
> Thank you for your work on ffupdater.

Thanks :)

This was the culprit a4bd19986bfa97024b60666ebd90ea635375daab

Fixed version 75.2.1 is now released. I've not notice this error because the Android emulator has not triggered the bug.

**Comment by rahrah** [comment]
Hi,

Thanks for the speedy fix!  

I can confirm things now work well on the de-googled phones I tested.

> This was the culprit https://github.com/Tobi823/ffupdater/commit/a4bd19986bfa97024b60666ebd90ea635375daab

Thank you for the info!  I considered doing a bisection, but the commits are quite big, and felt it might not help.

Once again, thank again for your work on this project and for making it open source.

All the best,

===Rich

**Comment by Tobi823** [comment]
>  I considered doing a bisection, but the commits are quite big, and felt it might not help.

I was a bit lazy creating commits with a good message - that's why I squash them into one commit.

In the future I will try to create smaller commits with even better commit messages. I want to improve myself and that can help finding bugs.
