### ISSUE TITLE
New localization

### ISSUE THREAD

**Issue by StoyanDimitrov** [Tobi823/ffupdater#13]
Apart from new, translated `values-xx\strings.xml` what other is needed for new localization to be accepted?

**Comment by Tobi823** [comment]
Nothing :)

Only the `values/string.xml` (https://github.com/Tobi823/ffupdater/blob/master/ffupdater/src/main/res/values/strings.xml) must be translated into a new language.

**Comment by StoyanDimitrov** [comment]
I guess this issue could be resolved by merging #14

**Comment by Tobi823** [comment]
Thanks for your contribution! 

I'm in the progress of adding new features to the app in the branch `improvements`.
Can you help me again with the Bulgarian translation in 1-2 weeks? (I guess that 20 strings have to be translated again)

**Comment by StoyanDimitrov** [comment]
Yes, count me in.

**Comment by Tobi823** [comment]
I'm going to release version 70.0.0 in the next days - can you test the app and check the translation? (latest commit on master)

**Comment by StoyanDimitrov** [comment]
The updated translation should be #15. Unfortunately can not help testing the app (exams).

**Comment by Tobi823** [comment]
No problem - thanks for your work :+1:
