### ISSUE TITLE
Add Mull browser

### ISSUE THREAD

**Issue by CodeCubeNeo** [Tobi823/ffupdater#130]
Hello. I think it would be really coll to add a firefox fork, that aims to remove the proprietary bloat: https://gitlab.com/divested-mobile/mull-fenix.

**Comment by Tobi823** [comment]
I move the discussion to https://github.com/Tobi823/ffupdater/discussions/157. 

Why don't you just install the Mull Browser with the F-Droid app? Did i miss something?

**Comment by strider72** [comment]
F-Droid can sometimes be slow to update apps. Pulling direct from developer releases is often faster -- by days.
