### ISSUE TITLE
Using a translation platform

### ISSUE THREAD

**Issue by StoyanDimitrov** [Tobi823/ffupdater#133]
Have you ever thought about using a translation platform to handle app translations?

I can warmly recommend [Weblate](https://hosted.weblate.org). After the initial project setup it is a matter of a `push` to send work to translators and a `pull` to get the latest translations. That's the manual mode...

I'm asking because this will **greatly** improve translators workflow for the project.

**Comment by Tobi823** [comment]
> Have you ever thought about using a translation platform to handle app translations?

Years ago I was looking for a good solution, but didn't find any free providers.

I've just created an account on weblate.org and discovered that maybe I can get it for free if FFUpdater meets all requirements for a libre project.

> I can warmly recommend Weblate. After the initial project setup it is a matter of a push to send work to translators and a pull to get the latest translations. That's the manual mode...

Sound very interesting :)

> I'm asking because this will greatly improve translators workflow for the project.

definitely, there is no doubt about it

**Comment by StoyanDimitrov** [comment]
Will, I guess just forgot to mention that the service is provided free for FOSS projects.

**Comment by StoyanDimitrov** [comment]
Thank you for the way you've configured the translation! Thank you for taking care to lock up old changelog entries and took the time to remove untranslated source texts from translations!

**Comment by Tobi823** [comment]
Thanks :)

I noticed that ersen has translated a lot of old changelogs into Turkish - and I thought it would be better if I lock the old changelogs so that the work goes in where it will bring the most benefit.

Weblate supports "Bulk edit" - with one command I was able to lock all changelogs and then manually unlock the latest one: https://docs.weblate.org/en/latest/admin/addons.html?highlight=has%3Alabel#id2

**Comment by Tobi823** [comment]
I hope that Weblate will host the Weblate-FFUpdater-project for free. I summited a "Libre hosting" request last Wednesday and have not received a response yet. 

Maybe I should not be so impatient - the trial will not expire for another 10 days

**Comment by StoyanDimitrov** [comment]
I don't think there is a reason for concern.

**Comment by Tobi823** [comment]
You were right - they have just approved the hosting.

Using Weblate was a very good idea - thanks :)

>Hi Tobias,
>
>Welcome to the community! Your hosting request has been approved, and you can now use Weblate.
>
>Don’t forget to mention you use Weblate in the README and the website of your project! You can use the lovely stuff from the Share menu of your Weblate project for it.
>
>The free hosting still costs us some money. If you're in a position to do that, you are welcome to support Weblate in providing this service to libre projects for free:
>https://weblate.org/donate/
>
>Kind regards,
