### ISSUE TITLE
New browsers

### ISSUE THREAD

**Issue by Tobi823** [Tobi823/ffupdater#156]
I want to use the Discussions area to discuss whether a particular browser should be added to FFUpdater. I hope that other people will provide good reasons for or against it.

If you think, that your favourite browser should be added to FFUpdater, please open a new discussion (https://github.com/Tobi823/ffupdater/discussions) with the category "Idea".

**Comment by eisklwksjs** [comment]
Well, as Bromite is outdated, one among the two developers decided to continue it's legacy with some improvements, with "cromite". It inherits privacy from bromite.....check this 
https://github.com/uazo/cromite
