### ISSUE TITLE
FFupdater not showing new version for "normal" Firefox

### ISSUE THREAD

**Issue by H-Sachse** [Tobi823/ffupdater#16]
FFUpdater 70.0.0 does not show new version number for updatable Firefox:
![Screenshot_20201113-204112](https://user-images.githubusercontent.com/67382933/99114522-387d1680-25f1-11eb-94f1-5b3782978f74.png)

**Comment by Tobi823** [comment]
This is a limitation of the Mozilla-CI server.

I can only query the timestamp of the latest Firefox release - nothing more (see https://firefoxci.taskcluster-artifacts.net/b90qoOBpSgKOb7ncSEiAoQ/0/public/chain-of-trust.json).

**Comment by Tobi823** [comment]
I've updated the README + text in F-Droid

**Comment by H-Sachse** [comment]
Maybe ask the Mozilla guys to put the version number into the info file? Right now it is totally unclear if the update is only a bugfix or a major version change that may break things. I really don't like installing updates blindly.

**Comment by Tobi823** [comment]
I discovered that I can extract the version number by parsing the chain_of_trust.log from Mozilla.

FFUpdater 71.0.0 will implement your feature request.
