### ISSUE TITLE
(Feature request) Remove warning flag thing.

### ISSUE THREAD

**Issue by splice11** [Tobi823/ffupdater#165]
![012cf91c-7d03-4d8f-b64f-70beb497334b](https://user-images.githubusercontent.com/92755960/166691226-bb5e0be0-f694-45d8-bb34-05f2fd043724.jpeg)

Can we get rig of the "problems" warning? I think one warning is enough when installing. Why keep warning when the user already knows...

**Comment by Tobi823** [comment]
> Why keep warning when the user already knows

Because the warnings may change. But you are right - it is unlikely and it is annoying.

**Comment by Tobi823** [comment]
It's now implemented in version 75.5.3
