### ISSUE TITLE
Support for Iceraven

### ISSUE THREAD

**Issue by CharmCityCrab** [Tobi823/ffupdater#17]
Iceraven is an open-source Firefox for Android fork dedicated to providing users more options, customizations, extendability, and information about how their browser interacts with the websites they visit (and vice-versa) than upstream Firefox.

It also *tries* to strip out proprietary telemetry as much as possible.   Some of the code for that is based on the F-Droid Fennec code.

Anyhow, they've been trying to get listed in F-Droid since at least August, and haven't quite been able to get it done (See https://github.com/fork-maintainers/iceraven-browser/issues/26 ).

Right now, it releases exclusively through Github.

Is there any chance that the .apk files from https://github.com/fork-maintainers/iceraven-browser/releases could be added to your updater?

Iceraven is not a Mozilla release, but it is a close fork, and I note that you already have, or have in the past had, the ability to support multiple browsers (i.e. All the different Mozilla browsers that have been at times available simultaneously).

I'm not asking this as any kind of official representative, just as a fan of Iceraven.  They're short on people who can do the real coding work, so I try to run around online doing stuff like this on my own initiative. ;)

I'm tagging Iceraven's lead developer- @interfect - as a courtesy, but just so that he is aware of this thread, not to pull his attention towards getting it done.  Right now he's the only developer and has to balance that with a separate full time job and a life, so he may want to, you know, develop the browser with the limited amount of time he has (Incidentally, Iceraven welcomes volunteer coders either at the level of potential project maintainers or just to submit some patches and pull requests, which could be as simple as merging from upstream stable.  Folks who don't mind doing CI testing would be particularly welcome.) rather than engaging in discussion on another project's GitHub, but I think this is something he'd approve of as at least a temporary solution if @Tobi823 is willing to do it.

If you're not comfortable listing it because of potential confusion with official Mozilla releases, you could always consider listing it in a way that makes it's status clear within the updater with something along the lines of  "Iceraven (Not an official Mozilla release)".

**Comment by Tobi823** [comment]
Is there any chance that the .apk files from https://github.com/fork-maintainers/iceraven-browser/releases could be added to your updater?

Yes :smile: - I'm already using the GitHub-API for downloading/updating Firefox Lite and Lockwise. I can reuse my code, add some flavor text, add some tests etc. - should take me 1-6 hours. I will add Iceraven to FFUpdater because I want to support the use of privacy-friendly browsers (see my goals https://github.com/Tobi823/ffupdater/blob/master/GOALS.md).
But I'm currently busy (bachelor thesis) - I guess I need 1-2 weeks for this feature.

	so I try to run around online doing stuff like this on my own initiative.
:+1: 

	If you're not comfortable listing it because of potential confusion with official Mozilla releases, you could always consider listing it in a way that makes it's status clear within the updater with something along the lines of "Iceraven (Not an official Mozilla release)".
No hard feelings

**Comment by CharmCityCrab** [comment]
> Yes 😄 - I'm already using the GitHub-API for downloading/updating Firefox Lite and Lockwise. I can reuse my code, add some flavor text, add some tests etc. - should take me 1-6 hours. I will add Iceraven to FFUpdater because I want to support the use of privacy-friendly browsers (see my goals https://github.com/Tobi823/ffupdater/blob/master/GOALS.md).

Thanks!

**Comment by Tobi823** [comment]
FFUpdater 71.0.0 will support Iceraven.
But I have to do some cleanups -> either today or tomorrow I will trigger the release on F-Droid
