### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by mcepl** [Tobi823/ffupdater#176]
Stacktrace:
```
f4.u0: Job was cancelled; job=w0{CancelliStacktrace:
```
f4.u0: Job was cancelled; job=w0{Cancelling}@8407f9e
```
Device information:
| key | value |
| --- | --- |
| version name | 75.5.0 |
| version code | 102 |
| build type | release |
| SDK version | 30 |
| android release | 11 |
| board | MT6762 |
| brand | Nokia |
| device | ROGA_sprout |
| manufacturer | HMD Global |
| model | Nokia G10 |
| product | Rogue_00EEA |
| SOC manufacturer | / |
| SOC model | / |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1646851005000 |ng}@8407f9e
```
Device information:
| key | value |
| --- | --- |
| version name | 75.5.0 |
| version code | 102 |
| build type | release |
| SDK version | 30 |
| android release | 11 |
| board | MT6762 |
| brand | Nokia |
| device | ROGA_sprout |
| manufacturer | HMD Global |
| model | Nokia G10 |
| product | Rogue_00EEA |
| SOC manufacturer | / |
| SOC model | / |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1646851005000 |

**Comment by Tobi823** [comment]
Sorry, but I can't reproduce this error. If this error occurs regularly, comment on this closed issue and I will send you a version with more crash information.
