### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Lloir** [Tobi823/ffupdater#184]
Stacktrace:
```
de.marmaro.krt.ffupdater.security.FingerprintValidator$UnableCheckApkException: Can't find signatures of the APK file.
	at de.marmaro.krt.ffupdater.security.FingerprintValidator.checkApkFile(Unknown Source:58)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller.secureInstallAsync(Unknown Source:121)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller.access$secureInstallAsync(Unknown Source:0)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller$installAsync$2$1.invokeSuspend(Unknown Source:30)
	at t3.a.resumeWith(Unknown Source:8)
	at g4.d0.run(Unknown Source:94)
	at j4.a$a.run(SourceFile:9)
Caused by: de.marmaro.krt.ffupdater.download.ApkSignatureNotFoundException: PackageInfo has no signingInfo and no signatures.
	at de.marmaro.krt.ffupdater.download.PackageManagerUtil.extractSignature(SourceFile:8)
	at de.marmaro.krt.ffupdater.download.PackageManagerUtil.getPackageArchiveInfo(Unknown Source:45)
	at de.marmaro.krt.ffupdater.security.FingerprintValidator.checkApkFile(Unknown Source:26)
	... 6 more
Timestamp: 2022-06-08T21:09:12.788

```
Device information:
| key | value |
| --- | --- |
| version name | 75.5.1 |
| version code | 103 |
| build type | release |
| SDK version | 33 |
| android release | 13 |
| board | sunfish |
| brand | google |
| device | sunfish |
| manufacturer | Google |
| model | Pixel 4a |
| product | sunfish |
| SOC manufacturer | Qualcomm |
| SOC model | SM7150 |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1654229791000 |

**Comment by Lloir** [comment]
Only happens with firefox works fine with others

**Comment by Lloir** [comment]
Actually.....this might be a me problem...especially if you cant reproduce

**Comment by Tobi823** [comment]
> Only happens with firefox works fine with others

You mean the "normal" Firefox Browser? 

> Actually.....this might be a me problem...especially if you cant reproduce

I can't reproduce it on my Pixel 3a + Android 12 GrapheneOS. But there were other people who also have this issue sometimes.

Can you try rebooting your device? Maybe it helps?

But I have the feeling that I am missing something. According to the documentation https://developer.android.com/reference/android/content/pm/PackageManager#getPackageArchiveInfo(java.lang.String,%20int) getPackageArchiveInfo should return the 
signatures of the APK file - but it doesn't. And I am certain that Google has implemented the API correctly. 

(More notes to my self):
- Maybe the downloaded Firefox APK file is corrupted?
- Uses Mozilla some special signing method that will not work with getPackageArchiveInfo?
- Is the content of the APK file not fully written to disk when I call getPackageArchiveInfo()
- Maybe a bug in Android 13?
- Maybe a temporary bug?
- Did I need some special permission to extract the signature from an APK file?

**Comment by Tobi823** [comment]
(More notes to myself)

- I think that the APK file can be parsed by getPackageArchiveInfo because it returns an object and not null. (getPackageArchiveInfo returns : **A PackageInfo object containing information about the package archive. If the package could not be parsed, returns null.**)

**Comment by IconBunnyGoing** [comment]
Happened to me with Firefox Klar 101.2.0. Same stack trace.

**Comment by Tobi823** [comment]
Maybe I introduced a new logic bug which prevents newer devices to use the old (deprecated) API (for extracting signatures). Can you try version 75.1.2?

**Comment by IconBunnyGoing** [comment]
I think the bug prevented me from updating FFUpdater through itself. Had to install it manually. New version works. Installed FF Klar without error.
