### ISSUE TITLE
(Feature request) Allow auto-downloaded update to be installed without forcing check for newer version

### ISSUE THREAD

**Issue by philipmgrant** [Tobi823/ffupdater#192]
This behaviour may be by design, rather than a bug, but it might be good to add a setting to make it configurable.

Steps to reproduce:

1. Enable "Update check" and "Download updates" options in the settings
2. At some point, an update will be downloaded in the background and you get a notification, "click to install update"
3. Tap the notification
4. FFUpdater will always check for a newer update and try to download it.  If the check cannot be done, or the update can't be downloaded, it is not possible to install the version that was already downloaded.

I personally would rather be able to just install what was already downloaded.  If the update downloads overnight, I might get to the notification in the morning while commuting, with either no network access, or metered access only - so I want to just install what was already downloaded.

**Comment by Tobi823** [comment]
The "Update check" is essential to check if the available download is an already installed APK or a new APK file.

For example, for most apps I query the GitHub-API to check for updates (example: https://api.github.com/repos/brave/brave-browser/releases) . GitHub only returns these information - and with these information I have to decide if FFUpdater should download the file or not: 

```
[
  {
    ...
    "tag_name": "v1.40.105",
    ...
    "created_at": "2022-06-19T12:29:53Z",
    "published_at": "2022-06-19T13:58:26Z",
    "assets": [
      ...
      {
        ...
        "name": "Bravearm.apk",
        ...
        "size": 141977482,
        ...
        "created_at": "2022-06-19T13:58:34Z",
        "updated_at": "2022-06-19T13:58:42Z",
        "browser_download_url": "https://github.com/brave/brave-browser/releases/download/v1.40.105/Bravearm.apk"
      },
      ...
    ]
  },
  ...
]
```

Without the "Update check" FFUpdater have to download an APK file for every installed app every x hours. And that would be a big waste of mobile data and server traffic.

I do not know if I have understood you correctly ... but what should be the benefit in disabling the update check?

**Comment by philipmgrant** [comment]
> I do not know if I have understood you correctly ... but what should be the benefit in disabling the update check?

So let's say FFUpdater auto-downloaded a Firefox Nightly update for me in the night, according to the schedule I configured.

I get to my phone in the morning, and see the notification.  Now, I just want to install that downloaded version.  I know it might not be the latest one, and that's fine with me: I'm happy to install it anyway.

So the benefit for me would be that in the morning, if I don't have unmetered network access, I can still install what was downloaded overnight.

> The "Update check" is essential to check if the available download is an already installed APK or a new APK file.

I think that's true for a user who wants to be sure the version they are installing is the absolute latest: but for me it's not essential.

**Comment by Tobi823** [comment]
> So let's say FFUpdater auto-downloaded a Firefox Nightly update for me in the night, according to the schedule I configured.

> I get to my phone in the morning, and see the notification. Now, I just want to install that downloaded version. I know it might not be the latest one, and that's fine with me: I'm happy to install it anyway.

> So the benefit for me would be that in the morning, if I don't have unmetered network access, I can still install what was downloaded overnight.

So you want to download the latest APK file for e.g. Firefox in the night and install the downloaded APK file in the morning? Even if you reinstall the same version of Firefox (and thus get no benefit)?

**Comment by philipmgrant** [comment]
> So you want to download the latest APK file for e.g. Firefox in the night and install the downloaded APK file in the morning? Even if you reinstall the same version of Firefox (and thus get no benefit)?

Sorry, I didn't make it clear.

The current workflow is something like this:

1. It's time for a scheduled update.

2. FFUpdater compares the latest version available on the server to the installed version.  If they are the same, it doesn't proceed.

3. (Assuming the version on the server is newer), FFUpdater downloads the server version and sends a notification.

4. Some time later, I tap the notification.

5. FFUpdater checks **again** to compare the latest version on the server to the **downloaded** version. 

6. If the version on the server is the same as the downloaded version, FFUpdater installs the downloaded version.


Now, **step 2** makes sense and I'm not suggesting removing that.  But I would like the option to **bypass step 5**.  If something was downloaded, I want to be able to install that, even if by the time I install it it is no longer the latest.

At the moment the problems are:

a. If I have no network at step 5, the check cannot happen and I cannot install the update that was already downloaded.

b. If I have only a metered network at step 5, and a newer version exists, I'm paying for an extra download I'd rather avoid.

**Comment by Tobi823** [comment]
Now I understand your problem.

Solution: I should pass the download URL + other metadata to the notification. When you click on the notification, these metadata should be passed to the InstallActivity (the user interface for downloading + installing updates). 

With these metdata, InstallActivity does not have to call the update check to get the download URL.

**Comment by Tobi823** [comment]
Step 5 (FFUpdater checks again to compare the latest version on the server to the downloaded version.) can and should be avoided.

**Comment by philipmgrant** [comment]
> Now I understand your problem.
> 
> Solution: I should pass the download URL + other metadata to the notification. When you click on the notification, these metadata should be passed to the InstallActivity (the user interface for downloading + installing updates).
> 
> With these metdata, InstallActivity does not have to call the update check to get the download URL.

Sounds great, thank you!  And thanks very much for all your work on the app - it makes managing Firefox Nightly without Play Store way easier!

**Comment by Tobi823** [comment]
[ffupdater-release.zip](https://github.com/Tobi823/ffupdater/files/8936177/ffupdater-release.zip)


The download URL and other metadata are now cached in the "Update is available" notification. If you click on it, FFUpdater should use these metadata and install the already downloaded APK file.

Can you verify that it works now?

**Comment by philipmgrant** [comment]
> [ffupdater-release.zip](https://github.com/Tobi823/ffupdater/files/8936177/ffupdater-release.zip)
> 
> The download URL and other metadata are now cached in the "Update is available" notification. If you click on it, FFUpdater should use these metadata and install the already downloaded APK file.
> 
> Can you verify that it works now?

Thanks for the quick turnaround!  Unfortunately it's not quite working right for me: I get a notification "Downloading app updates...downloading update for Firefox Nightly (_X_%)" which persists even after it reaches 100%, and doesn't do anything when I tap it.

I'm not sure if this is related to the fix for this issue or if it has a different cause.

**Comment by Tobi823** [comment]
The "Downloading app updates" is not clickable. It should only inform the user that FFUpdater is downloading the APK file in the background.

And I found a bug - the background update checker ignores app if the APK file was already downloaded. That's why you did not see the clickable "Update for XXX available - Click to install update"

**Comment by Tobi823** [comment]
[ffupdater-release.zip](https://github.com/Tobi823/ffupdater/files/8936362/ffupdater-release.zip)

Can you try it again?

**Comment by philipmgrant** [comment]
> [ffupdater-release.zip](https://github.com/Tobi823/ffupdater/files/8936362/ffupdater-release.zip)
> 
> Can you try it again?

This version is looking good from my first test. I'll keep an eye on it and check it continues behaving as expected.  Thanks again!

**Comment by philipmgrant** [comment]
I did find one issue.  I got a notification for a downloaded update and then tapped it when I was disconnected from wifi. (I have the "Update checks on metered networks" and "Download app updates on metered network options disabled.)

When I tapped the notification, FFUpdater showed an error "No metered network" and could not complete the installation.  So it  could be that a check is still being made against the remote server?

**Comment by philipmgrant** [comment]
> Should be now fixed in 76.0.1

I updated to 76.0.1 and tested but unfortunately I still see this issue.  Steps to reproduce:

1. Configure settings so that updates will download in the background
2. Wait for a notification that an update is ready to install
3. Put the phone into airplane mode
4. Tap the notification
5. A message appears "No unmetered network,  You can now close this window" with no way of installing the update.

**Comment by Tobi823** [comment]
Should be fixed in the next version - (now InstallActivity will always use the cached update information)

**Comment by Tobi823** [comment]
Try the new version 77.0.0 - should be fixed now.

**Comment by philipmgrant** [comment]
> Try the new version 77.0.0 - should be fixed now.

It works! Many thanks for all your work on this!!

**Comment by Tobi823** [comment]
Thanks :)
