### ISSUE TITLE
Remove Ungoogled Chromium (and maybe IceRaven as well)

### ISSUE THREAD

**Issue by p0yskaa** [Tobi823/ffupdater#198]
It appears that the Android version of Ungoogled Chromium has been discontinued: https://github.com/ungoogled-software/ungoogled-chromium-android
Also IceRaven builds are failing and the last version came out in May: https://github.com/fork-maintainers/iceraven-browser
It's missing security updates so it's not very safe to use.

It would be best to remove them and make changes to the README

**Comment by Tobi823** [comment]
I agree - the two browsers are no longer safe to use and should be marked as end-of-life. I can revert this step if the developers release a new version

**Comment by p0yskaa** [comment]
> I agree - the two browsers are no longer safe to use and should be marked as end-of-life. I can revert this step if the developers release a new version
Perfect. Should I close the issue right now or once the new version comes out?

**Comment by Tobi823** [comment]
I can close it when I've done the code changes

**Comment by Tobi823** [comment]
Done. Iceraven and Ungoogled Chromium are temporary removed in version 77.0.0.
