### ISSUE TITLE
Nightly URL is broken

### ISSUE THREAD

**Issue by dannycolin** [Tobi823/ffupdater#2]
The download link for Nightly is different than the path in Mozilla archive.

It seems like they've changed it to : 
`https://archive.mozilla.org/pub/mobile/nightly/latest-mozilla-esr68-android-api-16/`

I guess the name will change again when ESR 68 will hit its End of Life.

**Comment by Tobi823** [comment]
Thanks for the info.

I discovered some new URLs for downloading the nightly build:

https://download.mozilla.org/?product=fennec-nightly-latest&os=android&lang=multi
https://download.mozilla.org/?product=fennec-nightly-latest&os=android-x86&lang=multi

(I'm pretty sure that's new. One year ago, the links from https://www.mozilla.org/de/firefox/android/nightly/all/ were different and contained the version number)

I will fix that as soon as possible.

**Comment by Tobi823** [comment]
I created a new version (67.0) containing the fix for the broken nightly download. But it will take 1-3 days until F-Droid will distribute the new verison.

If there is any problem left, please free to open a new issue or reopen this issue.

**Comment by dannycolin** [comment]
Thanks.
