### ISSUE TITLE
Can you guys add Via Browser as well?

### ISSUE THREAD

**Issue by Taratect** [Tobi823/ffupdater#208]
This is their link
https://github.com/tuyafeng/Via

I am wondering how good this browser is on the privacy side and it'd be nice if it was updated automatically

**Comment by SkewedZeppelin** [comment]
Via browser is proprietary and contains an advertising/tracking library from Verizon.
https://reports.exodus-privacy.eu.org/en/reports/mark.via.gp/latest/

**Comment by Tobi823** [comment]
@Taratect Sorry, but Via is not a good candidate for FFUpdater. The only privacy feature on their GitHub-Page is ad blocking. For me, that is too little.

But you can use other projects (for example the Aurora Store https://f-droid.org/en/packages/com.aurora.store/) to update your Via browser.

(And thanks @SkewedZeppelin for the details 👍🏻 )
