### ISSUE TITLE
Add Tor Browser for Android

### ISSUE THREAD

**Issue by SkewedZeppelin** [Tobi823/ffupdater#210]
Tor Browser is currently re-distributed in the Guardian Project F-Droid repo.
However such repo is included by default in the official F-Droid app disabled.
But Tor Browser (and the previous Orfox) contain proprietary blobs, which from my understanding violates such inclusion agreement.
https://gitlab.com/guardianproject/fdroid-metadata/-/issues/3

It'd be nice to see the official Tor Browser for Android app listed in FFUpdater.
And this would provide a path for users to still easily receive updates for it.
There should be no signature issues as GP isn't compiling/signing the builds.

Additionally since the app could always fetch the latest it would remove the delay there currently is between Tor Project marking a release and GP importing it to their repository.

Lastly given the verification FFUpdater performs, it'd be a safer way than simply downloading the APK from torproject.org as most users (would) do.

It'd kill three birds with one stone. :smiley:

**Comment by Tobi823** [comment]
I move the discussion to https://github.com/Tobi823/ffupdater/discussions/212.
