### ISSUE TITLE
(Suggestion) Add info and warn icon+message to browser add menu

### ISSUE THREAD

**Issue by tdiekel** [Tobi823/ffupdater#214]
Hey, 

first off nice app. I just found it and was curious what the differences between the various browsers were since I got a warning for bromite. In the browser add menu I get the info and warning only if I click on an option which was nothing I foresaw.

So my suggestion is to add the warning and info fro the main screen the to browser add menu. Maybe also a link to the respective repos for further information.

If you are interested I might be able to create a pull request with that change. But my android knowledge is somewhat dated.

Best regards

**Comment by Tobi823** [comment]
I am busy with university right now. I will check in later.

**Comment by Tobi823** [comment]
> So my suggestion is to add the warning and info fro the main screen the to browser add menu.

Should already be implemented - or am I missing something?

When I click on the info icon: 
![info_icon](https://user-images.githubusercontent.com/10066140/188645190-b1195d24-fe07-4f89-a17f-77aa79ff7cc0.jpg)

When I click on the warning icon:
![warning_icon](https://user-images.githubusercontent.com/10066140/188645259-4c747711-fdd8-47c4-8d36-3a8dbec842d2.jpg)

When I install a new app:
![installation1](https://user-images.githubusercontent.com/10066140/188645309-6bf2d402-b0a2-4a5f-9028-c9d80082c4e5.jpg)
![installation2](https://user-images.githubusercontent.com/10066140/188645329-07dab7c6-2e7d-45b5-a8bd-06170528aef9.jpg)

Chaining these two dialog boxes together is not ideal, maybe I find a better solution.

>  Maybe also a link to the respective repos for further information.

That's a good idea. I will think about it.

> If you are interested I might be able to create a pull request with that change. But my android knowledge is somewhat dated.

Thanks for the offer - but I still have to think about how to improve the UI there. I'll be in touch if I need your help.

**Comment by tdiekel** [comment]
> > So my suggestion is to add the warning and info from the main screen the to browser add menu.
> 
> Should already be implemented - or am I missing something?

My problem when I opened the list of apps was that I were not familiar with all of them. I would have liked a quick way to get some basic information about the apps without having to cycle through the following for all apps: `Install -> App A -> Read warning -> Dismiss -> Install -> App B -> ...`. My suggestions is to add the button and the corresponding dialog boxes from the main menu

<img src="https://user-images.githubusercontent.com/29117884/189202759-77f146a9-2754-4579-89a9-a925b8683f24.jpg" width=50% height=50%>

to the available list of browsers 

<img src="https://user-images.githubusercontent.com/29117884/189202850-99365c1b-3b24-40cf-a1bf-e87ae6559de9.jpg" width=50% height=50%>

to make it easier for the user to choose the best fitting browser. Maybe its possible to reuse the code from [here](https://github.com/Tobi823/ffupdater/blob/master/ffupdater/src/main/java/de/marmaro/krt/ffupdater/MainActivity.kt#L148-L166). 

> Chaining these two dialog boxes together is not ideal, maybe I find a better solution.

The warning could/should still be presented when the user selects a browser to install. I see no need in chaining dialog boxes but maybe I'm missing something.

**Comment by Tobi823** [comment]
Done 
![Screenshot_20220909_203337](https://user-images.githubusercontent.com/10066140/189421368-46772529-8823-4537-983c-99ffe6960c4e.png)
