### ISSUE TITLE
Can't install new update Firefox Beta

### ISSUE THREAD

**Issue by skariko** [Tobi823/ffupdater#217]
Hello,
I have FFUpdater 77.1.0.

I have installed Firefox Beta, it shows me there is an update but if I try to update it says that I have already last version installed.

![Screenshot_20220809-213236](https://user-images.githubusercontent.com/25532821/183747687-f47a05fb-9f73-450a-b80b-fb12deee68e8.png)

here it says i have installed the b04 and is available the b05 but if I click on install button it says

![Screenshot_20220809-213710](https://user-images.githubusercontent.com/25532821/183747505-cdb9b3fb-dab8-4e49-94a6-ff9f4a2d1ff6.png)

But I have installed the b04, pretty sure:
![Screenshot_20220809-214520](https://user-images.githubusercontent.com/25532821/183747703-ba4baece-6d87-492a-ad61-07f163ac5da3.png)

Maybe is it a FFUpdater bug?

**Comment by skariko** [comment]
update: i try to install it anyway despite ffupdater telling me that I would overwrite the exact same version.

It worked and I now have b5, however the fact remains that it did not notify me of the update and thought I had already done it.

**Comment by Tobi823** [comment]
I am busy with university right now. I will check in later.

**Comment by Tobi823** [comment]
I can reproduce the error

**Comment by Tobi823** [comment]
Should be fixed now
