### ISSUE TITLE
Restore the Chromium download

### ISSUE THREAD

**Issue by careet** [Tobi823/ffupdater#218]
We know it's out of date and that some (superficial) security risks are involved. Adding a disclaimer was more than sufficient. There is no other good ungoogled chromium downloader for Android with a GUI, and honestly, this app is much more useful as an update checker/downloader than as Tobi823's personal, curated list of recommendations with notes and tips and all this other unnecessary stuff. Just leave it up and link to version 99.whatever until the dev finally, if ever, updates it. If people are dialed in enough to be able to download FDroid, root their device, and know they want to install a third party version of an open source browser, I'm sure they're competent enough to understand the security risks involved in downloading an out-of-date browser.

**Comment by Tobi823** [comment]
I am busy with university right now. I will check in later.

**Comment by Tobi823** [comment]
@Tobi823 idea: improve the layout for adding new browser (#214) and add a separate area for EoL browser.

**Comment by Tobi823** [comment]
Done 
![Screenshot_20220909_203131](https://user-images.githubusercontent.com/10066140/189421444-02edf326-d02d-46b7-89d2-0208e653a9ae.png)

**Comment by careet** [comment]
You're a king, thank you very much!
