### ISSUE TITLE
Maybe reset unused permissions in Android 13

### ISSUE THREAD

**Issue by Tobi823** [Tobi823/ffupdater#220]
https://developer.android.com/about/versions/13/features#developer-downgradable-permissions

Maybe revoke the "app installation" permissions after a successful installation/update? But is this really useful?

**Comment by ashutoshccet** [comment]
No, because ffupdater has a setting available to use session installer and it is already excellent for people to use while maintaining their permission privacy.

**Comment by Tobi823** [comment]
Thanks for the second opinion. Sadly it is far to easy to miss important development without input from other developers/users.
