### ISSUE TITLE
Brave download on Android 6.0

### ISSUE THREAD

**Issue by CH3CH2OH-fan** [Tobi823/ffupdater#222]
Hi, I'm using an old Android 6.0 tablet
FFupdater downloads the BraveMonoarm apk which is for Android 7+, I believe
Bravearm.apk is the correct file for older Android versions

**Comment by Tobi823** [comment]
I am busy with university right now. I will check in later.

**Comment by Tobi823** [comment]
> I believe Bravearm.apk is the correct file for older Android versions

Seems to be. It is fixed now.
