### ISSUE TITLE
[Request] Mulch - a chromium based browser

### ISSUE THREAD

**Issue by iamtalhaasghar** [Tobi823/ffupdater#223]
Divest Computing Group, the maintainers of Mull have just released "Mulch" which is a chromium based web browser. It is patched with GrapheneOS's Vanadium and Bromite.

Would be nice to have this listed in ffupdater as well.

What you all think?

Edit: https://gitlab.com/divested-mobile/mulch

**Comment by Tobi823** [comment]
done
