### ISSUE TITLE
Kiwi Browser is not displayed as supported on f-droid description

### ISSUE THREAD

**Issue by ppvnf** [Tobi823/ffupdater#231]
![WhatsApp Image 2022-09-21 at 16 18 01](https://user-images.githubusercontent.com/73800734/191597961-d00c62c8-5385-49b3-963c-ef7ab2ac339d.jpeg)

**Comment by chris122380** [comment]
This is either already fixed or a language translation issue.
![Uploading IMG_20220928_070641.jpg…]()

**Comment by chris122380** [comment]
This is either already fixed or a language translation issue.
![IMG_20220928_070641](https://user-images.githubusercontent.com/2205798/192786681-2e517e01-80ac-449a-ae37-74570bcd0442.jpg)

**Comment by ppvnf** [comment]
Thanks. I submitted the changes on https://hosted.weblate.org/translate/ffupdater/ffupdater-release-notes/pt_BR/?checksum=502bfece59e1216b

**Comment by Tobi823** [comment]
@ppvnf thanks for the fix
