### ISSUE TITLE
Brave browser is installing a 32-bit build instead of the 64-bit build

### ISSUE THREAD

**Issue by chris122380** [Tobi823/ffupdater#232]
Brave browser is installing a 32-bit build instead of the 64-bit build. I'm not sure if this has something to do with the brave GitHub version being pulled or what exactly. If you install Brave browser from the Google Play Store and go to chrome://version/ it says 64-bit but if you install the version from FFupdater under chrome://version/ it shows 32-bit.

**Comment by Tobi823** [comment]
It seems that Brave only offers 32bit builds.

I've downloaded and installed  BraveMonoarm64.apk from https://github.com/brave/brave-browser/releases/tag/v1.44.110 - but chrome://version/ still report that I'm running an 32bit build.

**Comment by chris122380** [comment]
> It seems that Brave only offers 32bit builds for Android.
> 
> I've downloaded and installed BraveMonoarm64.apk from https://github.com/brave/brave-browser/releases/tag/v1.44.110 - but chrome://version/ still report that I'm running an 32bit build.

This is the error I'm reporting. Brave from the Google Play store shows chrome://version as running 64bit build. Why isn't the GitHub version a 64bit build?

**Comment by Tobi823** [comment]
Good question. I found no further information except this forum question https://community.brave.com/t/chromium-64-bit-instead-of-32-bit-for-brave-android/145635
