### ISSUE TITLE
Add Orbot from the github repository

### ISSUE THREAD

**Issue by xyz-nobody** [Tobi823/ffupdater#234]
Hello,

I really like your application it's very useful.

I know it's not a browser but it's still linked :)
because it's super convenient to have access to some sites via the Browser :)

We can install it by hand, but it would be so cool to do it with FFUpdater

Could you please add Orbot from the github repository:

https://api.github.com/repos/guardianproject/orbot/releases/latest

Thanks in advance

**Comment by Tobi823** [comment]
Orbot is already supported by FFUpadater but I forgot to add it to the README.md
