### ISSUE TITLE
Additional installation method: Shizuku

### ISSUE THREAD

**Issue by muntasimfuad** [Tobi823/ffupdater#247]
**[Shizuku ](https://github.com/RikkaApps/Shizuku)** is a tool to use higher privileges using ADB on non-rooted devices. So It can be used as an option to install applications and updates in the background like the root installer on non-rooted devices.

Some apps that uses Shizuku to install  & updates apps on background :

- **[Droid-ify](https://github.com/Iamlooker/Droid-ify)**
- **[SAI](https://github.com/Aefyr/SAI)**
- **[Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)**

**Comment by Tobi823** [comment]
Sounds interesting. I will look into it.

**Comment by Tobi823** [comment]
Done. Will be part of the next release
