### ISSUE TITLE
Ffupdater has been crashing for me so I created a github to submit this crash report.

### ISSUE THREAD

**Issue by F-14TOMCAT** [Tobi823/ffupdater#268]
Stacktrace:
```
de.marmaro.krt.ffupdater.network.exceptions.InvalidApiResponseException: can't find release after all tries - abort
	at de.marmaro.krt.ffupdater.network.github.GithubConsumer.updateCheck(SourceFile:2)
	at de.marmaro.krt.ffupdater.network.github.GithubConsumer$updateCheck$1.invokeSuspend(Unknown Source:19)
	at w3.a.resumeWith(Unknown Source:8)
	at j4.i0.run(Unknown Source:100)
	at m4.d.run(Unknown Source:11)
	at n4.j.run(Unknown Source:2)
	at n4.a$a.run(SourceFile:82)
	Suppressed: j4.g0: [k1{Cancelling}@ee489c3, Dispatchers.Main]
Timestamp: 2022-11-03T07:58:06.876

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.3.1 (115) release |
| Device | HD1907 (OnePlus7TTMO, OnePlus7TTMO, msmnile) |
| Manufacturer | OnePlus (OnePlus) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 11 (SDK: 30) |
| OS | cndgdlbpdu03-140-21, OnePlus, release-keys, 1665851842000 |

**Comment by F-14TOMCAT** [comment]
Like I said, I'm new so I'll probably just uninstall/reinstall but I wanted to submit a crash report for once.

**Comment by Tobi823** [comment]
> Like I said, I'm new so I'll probably just uninstall/reinstall but I wanted to submit a crash report for once.
Thanks 👍🏻

I fixed the bug yesterday. The latest version (77.3.5) should work.
