### ISSUE TITLE
Exclude apps from update check no longer works

### ISSUE THREAD

**Issue by ovi-vansid** [Tobi823/ffupdater#272]
Since around version 77.3 (possibly earlier) the configuration 'Exclude apps from update check' is not respected.  Despite checking the boxes for several applications, they are still checked as if they are not excluded.  Tested on two different devices, same behavior.  Expected behavior is that updates for an excluded application are not checked.

**Comment by Tobi823** [comment]
> Despite checking the boxes for several applications, they are still checked as if they are not excluded.

Do you mean that excluded apps are check in the **background** for updates?

**Comment by ovi-vansid** [comment]
Yes, both foreground and background.  Several other supported apps were updated in the background despite being unchecked in the config screen.

**Comment by Tobi823** [comment]
I think there is an misunderstanding - this is an "ignore list". You only check the apps which should be ignored in the background update check. 

And the foreground update check is not affected by the setting. I think that I could be confusing if you can't update apps in the user interface.

**Comment by Tobi823** [comment]
![Screenshot_20221113_235630](https://user-images.githubusercontent.com/10066140/201549014-efa057ce-ec97-4df9-846d-da757bad99de.png)
![Screenshot_20221113_235653](https://user-images.githubusercontent.com/10066140/201549017-13183863-0d97-491f-bcd1-9ded482123e7.png)

In this example, FFUpdater will never check for Brave Browser (Beta) updates in the background.

Or I miss something?

**Comment by ovi-vansid** [comment]
I think I understand what may have happened.  A new version of FFUpdater included support for additional software application updates, such as Tor Browser.  However, after I upgraded to this new version, I did not return to the configuration and select the checkboxes for the new items.  Thus, they were upgraded in the background automatically, despite my incorrect assumption that only certain apps would be updated.

Having said that, I think the "Exclude" function should encompass both foreground and background applications.  Restricting the exclusion to the background only is confusing.

**Comment by Tobi823** [comment]
> Having said that, I think the "Exclude" function should encompass both foreground and background applications. Restricting the exclusion to the background only is confusing.

I disagree - I think it is more confusing when apps are in the foreground (the main user interface). If the user does not want to update an app, he simply must not press the update button.

**Comment by c33s** [comment]
please reopen/change the current behavior.

i am really thinking about downgrading ffupdater . i primary use f-droid to update my browsers. ffupdater is only for iceraven as the browser ist not available via fdroid. 

before the update i only had one update button. not much to think before press update but now all the browsers which i manage with fdroid also in the list. they also show an update button. 

as far as i know it would even be possible to loose bookmarks/user data if i install an app with a different signature. so showing browser which are excluded by the user is not only a bad UX, if i can loose data with it, it is a quite critical bug, isn't it?

please let us filter the listed browsers by the exclude list.
