### ISSUE TITLE
Please add an option to set a fixed CPU structure in setting for download

### ISSUE THREAD

**Issue by Rustlang4Future** [Tobi823/ffupdater#280]
Hello

Please add an option to set a fixed CPU structure in setting for download.

The use case for this is that some people like me may have low end or middle range phones that their kernel is 64 bit but the RAM amount isn't that much, so they may want to always download 32 bit version of browsers.

The default value for this can be auto and also you can warn people if they wanted to change it to prevent non-technical people mess with it.

But this will be a great life saver for someone like me.

Thank you very much for this great project.

**Comment by Tobi823** [comment]
I'm currently busy but I will do it
