### ISSUE TITLE
Please add an queue option so user can click to update all apps but they get downloaded one by one

### ISSUE THREAD

**Issue by Rustlang4Future** [Tobi823/ffupdater#281]
Hello

Please add an queue option so user can click to update all apps but they get downloaded one by one.

This will be great because users won't need to wait for every app to get downloaded and installed and then they click to download another one.

Currently people can set the app to download several apps simultaneously and the app warn them that this may result in lower speed and that's true for those that have low speed like me.

So, if you please add an option so that user can press update button of several apps, then they get downloaded and updated automatically one by one by FFUpdater itself, if will be great.

Also if it is possible please show the download and install progress in notification bar (somehow like aurora store maybe)

Thank you very much.
Best regards.

**Comment by Tobi823** [comment]
Idea: 
The update activity is started with a queue of apps. The activity will update the first element from the queue and remove it. If the update is successful, the update activity is restarted with the new queue.

Cons: Restarting an activity looks a little bit janky.

Pros: This solution is "simply" to implement and I can reuse most of the UI

**Comment by Tobi823** [comment]
This issue has a low priority because there are more important problems and many people (30 percent market share) have Android 12. (Android 12 can install updates in the background without interaction)

**Comment by Tobi823** [comment]
> Am i correct ? Please reply.

I decide not to implement this because:
- implementing takes some time
- this feature is harder to debug
- it makes FFUpdater more complex ad therefore more error prone
- and the usefulness is limited:
  - only rarely does a user install multiple apps at the same time. 
  - and the automatic background app update (with Android 12+, root permission or Shizuku) already uses a queue to update all outdated apps
