### ISSUE TITLE
Chromium 32-bit is not compatible with Pixel 7

### ISSUE THREAD

**Issue by jet082** [Tobi823/ffupdater#293]
As it says on the tin. Currently, the version fetched by ffupdater is the 32-bit version. Grabbing the URL directly and trying to install it says "App not installed as app is not compatible with your phone" and ffupdater throws a "fundamentally incompatible" error. See also https://www.reddit.com/r/Android/comments/y353es/google_seems_to_have_disabled_support_for_32bit/

For the Pixel 7 at least, the 64-bit binary is required.

**Comment by Tobi823** [comment]
That's surprising

**Comment by Tobi823** [comment]
The 64-bit version is also hosted on the site:

https://storage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Android_Arm64/1085969/

**Comment by Tobi823** [comment]
It was surprisingly easy to add support for 64-bit Chromium. This feature will be part of the next release in a few/couple days.
