### ISSUE TITLE
[Bug] arm64 version of Mulch is being downloaded even on armv7l device

### ISSUE THREAD

**Issue by nesper8** [Tobi823/ffupdater#294]

**Comment by Tobi823** [comment]
I think I fixed this bug yesterday evening. Can you try it again with version 77.4.0?

**Comment by Tobi823** [comment]
FYI This is the commit that should fix your issue https://github.com/Tobi823/ffupdater/commit/b1639f4edc7d4465a6c6e3af80dffc56315125af

**Comment by Tobi823** [comment]
Yes because Mull and Mulch share the same source code for update checking /downloading (the CustomRepositoryConsumer)
