### ISSUE TITLE
Code Review for FileDownloader.kt

### ISSUE THREAD

**Issue by Tobi823** [Tobi823/ffupdater#295]
Can someone check the source code in https://github.com/Tobi823/ffupdater/blob/master/ffupdater/src/main/java/de/marmaro/krt/ffupdater/network/FileDownloader.kt for bugs? 

I've done my best but a bug here would be dangerous.

**Comment by Enrico204** [comment]
I'm not proficient with Kotlin - I can't see any obvious bug or potential issue :-)
