### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Saicobo** [Tobi823/ffupdater#297]
Why do I get a security message: FFupdater has violated your application security policy automatically . ( StrictMode )

**Comment by Tobi823** [comment]
The StrictMode checks if FFUpdater is running correctly.

In the debug builds (which are not publish) the StrictMode is very thorough to detect leaking memory etc. The released versions uses a less thorough StrictMode.

FYI You should only see this error dialog in these cases:

- network access from Main thread
- slow method is called
- resource types and getter have different types
- input/output operations are not buffered

When did you see this warning dialog? Did you change same settings?

**Comment by Saicobo** [comment]
Thank you for answering and solving my doubt. keep it up i love this project 😊
