### ISSUE TITLE
Adaptive Icon

### ISSUE THREAD

**Issue by xmha97** [Tobi823/ffupdater#305]
Please use an adaptive icon.

![IMG_20230105_035150_252.jpg](https://user-images.githubusercontent.com/23485114/210674415-44293c69-1043-438d-8e8a-64848a96b648.jpg)

**Comment by Tobi823** [comment]
It was surprisingly hard to find a launcher in F-Droid that uses square icons. After almost ten tries I found Posion

**Comment by Tobi823** [comment]
![Screenshot_20230105-185727](https://user-images.githubusercontent.com/10066140/210849190-319af48c-ce5b-4cbd-b505-40e2d2dda366.jpg)

**Comment by Tobi823** [comment]
It's fixed now and will part of the next release (maybe 77.7.0)

**Comment by xmha97** [comment]
> ![Screenshot_20230105-185727](https://user-images.githubusercontent.com/10066140/210849190-319af48c-ce5b-4cbd-b505-40e2d2dda366.jpg)
> 

What's this launcher? (Send me F-Droid link)
