### ISSUE TITLE
Bug in Firefox Klar version check

### ISSUE THREAD

**Issue by Enrico204** [Tobi823/ffupdater#307]
After the switch to the new Mozilla repository for Firefox Klar, the app seems confused on version comparison (I suspect because Mozilla changed the way they report the version).

Currently, I have the version 108.2.0, and FFUpdater is notifying me that a new version is available, which is not. The "new" version is `klar-v108.2.0`. Note the prefix `klar-v` which is missing from the locally installed version.

![Screenshot_20230107-003627_FFUpdater](https://user-images.githubusercontent.com/8115660/211118306-8fe31bd2-44d0-4cbe-92eb-5dd9a6112d88.png)

**Comment by Tobi823** [comment]
Thanks for the info - I will fix it

**Comment by Tobi823** [comment]
Fixed version 77.6.3 is now released.

**Comment by Enrico204** [comment]
Thanks! I can confirm that now it's working properly:

![Screenshot_20230107-013206_FFUpdater](https://user-images.githubusercontent.com/8115660/211122000-a9ca6267-beb8-48f5-94c6-538dbd8e75e4.png)
