### ISSUE TITLE
Firefox Klar: update repeatedly wanted

### ISSUE THREAD

**Issue by jolly-jump** [Tobi823/ffupdater#308]
Hi. 
Since the latest update (I hope and think I updated from F-Droid and not from the /e/-OS - "Apps" updater, which might have pulled from the play store?)
I have two problems: Firefox Klar (from the new location in github) is correctly installed, but then the update-information differs from what is installed ("108.2.0" vs. "klar-v108.2.0") which (then, I guess) leads to wanting to update Firefox Klar again and again.

The second is the "FFUpdater" app seems to be "signed by a different certificate and can't be updated with FFUpdater". I don't know how that happened.
I updated just now using F-Droid-App and F-droid-Repo.

hope this and the appended pictures help help.

![threema-20230107-144246257](https://user-images.githubusercontent.com/2824334/211153959-a7e436b8-aa82-4e91-8506-fb8f3ccd60bf.png)
![threema-20230107-144245694](https://user-images.githubusercontent.com/2824334/211153967-a030a7b8-8f3c-4ac2-aee8-a0ce4abc761e.png)

**Comment by jolly-jump** [comment]
addendum: Version is 77.6.1(123) from 6.Jan.2023 on an Android 11 lineage-os-based /e/-OS.

I have one more bug report with a stacktrace following but I withhold a new bug report if this turns out to be my installation only.

The crash appears when clicking on any new browser to install and then clicking on the yellow warning triangle.
```
java.lang.IllegalArgumentException: Required value was null.
	at de.marmaro.krt.ffupdater.dialog.AppWarningDialog$Companion.newInstance(Unknown Source:46)
	at de.marmaro.krt.ffupdater.AddAppActivity$AvailableAppsAdapter.onBindViewHolderApp$lambda-1(Unknown Source:12)
	at de.marmaro.krt.ffupdater.AddAppActivity$AvailableAppsAdapter.c(Unknown Source:0)
	at de.marmaro.krt.ffupdater.a.onClick(Unknown Source:10)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28305)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Timestamp: 2023-01-07T14:52:31.424

```

**Comment by Tobi823** [comment]
These two bugs #306 #307  should already be fixed in version 77.6.3. Can you upgrade the app and check this fixes your issues?

**Comment by jolly-jump** [comment]
Hi. Thanks. Sorry for not checking the closed issues list, where I would have found the already filed issues.

And thanks for the solution: 
- for me, adding your f-droid repo did not show 77.6.2/3, only 77.6.1 and furthermore calls it now "unknown application". 
- download + install from the github releases worked. I could not find an apk file on gitlab, thus github.

One last remark: the multitude of installations (f-droid main, f-droid your added repo, dl+install, and from within the app (if i understand correctly)) and git-repos (github, gitlab, notabug) is - hm - overwhelming.
Well, after I read the whole readme (found the main repo, found the main distribution channel), there is nothing left to ask for.

**Comment by Tobi823** [comment]
> for me, adding your f-droid repo did not show 77.6.2/3, only 77.6.1 and furthermore calls it now "unknown application". 
I had to reinstall the software to update the F-Droid repository and forget to add the short app summary. But this is now fixed (I checked today on my smartphone)

> I could not find an apk file on gitlab, thus github. 
This is really hidden on Gitlab (see https://gitlab.com/Tobiwan/ffupdater_gitlab/-/releases/77.6.3) I will updat the link in the README.md.

> One last remark: the multitude of installations (f-droid main, f-droid your added repo, dl+install, and from within the app (if i understand correctly)) and git-repos (github, gitlab, notabug) is - hm - overwhelming.
You are right - I should split the README in smaller parts
