### ISSUE TITLE
Don't display Mulch as "Good Privacy Browsers"

### ISSUE THREAD

**Issue by d4f5409d** [Tobi823/ffupdater#314]
The title is misleading because in the source code's readme there's that being a privacy browser is out of their scope. Mulch is a "Good Security Browser" instead.

**Comment by Tobi823** [comment]
Creating a new category "Good Privacy Browser" is difficult because some apps like the Tor browser would be in both categories (because the Tor browser aims to be a privacy and a secure browser).

I have to think about it.

**Comment by d4f5409d** [comment]
> Creating a new category "Good Privacy Browser" is difficult because some apps like the Tor browser would be in both categories (because the Tor browser aims to be a privacy and a secure browser).
> 
> I have to think about it.

I meant to create "Good Security Browser" category

**Comment by SkewedZeppelin** [comment]
@d4f5409d 

While the focus is security, it still does have privacy features like state partitioning enabled by default among other things.

**Comment by d4f5409d** [comment]
Guys, I checked their repo. _They told us **DO NOT USE** the browser if we want a **PRIVACY** browser._ It's a **security browser** as the original developers intended. If you're trying to convince me I'm wrong, please just don't falsify **FACTS**. Thank you.

https://gitlab.com/divested-mobile/mulch

> "Becoming a "privacy" browser is out of scope, use Mull instead"

**Comment by d4f5409d** [comment]
> ### Generally, Ad-blockers (Contents blockers) are Privacy Browsers (automatically, yet still license check is also one thing or matter).
> 
> And NON Ad-blockers are "Security Browsers" ; Also sometimes called 'Vanilla Browsers.' If the Source Code is viewable and verifiable, open in public domain alongwith license.

Not really. It depends on what filters are enabled. When it's EasyPrivacy, I can agree.

**Comment by SkewedZeppelin** [comment]
> Guys, I checked their repo.

@d4f5409d 
Mull and Mulch are my projects.

**Comment by d4f5409d** [comment]
> > Guys, I checked their repo.
> > If you're trying to convince me I'm wrong, please just don't falsify FACTS
> 
> @d4f5409d 
> Mull and Mulch _are my projects_.

Sorry brother

**Comment by d4f5409d** [comment]
Thank you, this is what I wanted to tell you 6 months ago already :)
