### ISSUE TITLE
not getting notifications?

### ISSUE THREAD

**Issue by TotalChaos05** [Tobi823/ffupdater#318]
not sure what happened, but ever since I updated to a13 I haven't gotten notifications.
I've cleared cache/data, and reinstalled but nothing seems to work.

device: z flip 4
android: 13
oneui: 5
security patch: December 1, 2022
GPlay system: November 1, 2022

**Comment by TotalChaos05** [comment]
to give it notification perms i have to click "show system apps" in the notification permissions manager.
maybe itll work now?

**Comment by Tobi823** [comment]
#219

**Comment by Tobi823** [comment]
I forgot / had not the time to implement this

**Comment by Tobi823** [comment]
I try to fix it tomorrow

**Comment by Tobi823** [comment]
> to give it notification perms i have to click "show system apps" in the notification permissions manager.
maybe itll work now?

Maybe, I dont know :D

**Comment by TotalChaos05** [comment]
it didnt end up working :(
If I need to I can try to fix it, I just havent dont much work wth Android apps

**Comment by Tobi823** [comment]
it is fixed now
