### ISSUE TITLE
Brave not updating.

### ISSUE THREAD

**Issue by Cheechoz** [Tobi823/ffupdater#323]
There have been several releases and it still shows a release from 12/14/22.

**Comment by Tobi823** [comment]
I can't reproduce the problem - does the problem still persist? Do you update FFUpdater to 77.7.0?

**Comment by Cheechoz** [comment]
Yes I am on 77.7.0 and it's working fine now I'm on the latest Brave Beta , but I have a question,  why does the Google play store update the same version that I get from Github?

Jan 31, 2023 5:03:52 PM Tobias Hellmann ***@***.***>:

**Comment by Tobi823** [comment]
> why does the Google play store update the same version that I get from Github

Good question. I suspect that Brave Beta from GitHub and Google Play is signed by the same cryptographic key. So basically it is the same app.
