### ISSUE TITLE
FFUpdater should not download updates in the background when the data saver is turned on

### ISSUE THREAD

**Issue by Tobi823** [Tobi823/ffupdater#329]
> I also am getting frequent background errors, just in the last couple days:
> 
> `Stacktrace:
> 
> ```
> de.marmaro.krt.ffupdater.background.BackgroundException: The background job fails due to an unrecoverable exception.
> 	at de.marmaro.krt.ffupdater.BackgroundJob.handleDoWorkException(SourceFile:44)
> 	at de.marmaro.krt.ffupdater.BackgroundJob.access$handleDoWorkException(Unknown Source:0)
> 	at de.marmaro.krt.ffupdater.BackgroundJob$doWork$2.invokeSuspend(Unknown Source:59)
> 	at z3.a.resumeWith(Unknown Source:8)
> 	at l4.l0.run(Unknown Source:100)
> 	at r4.a$a.run(SourceFile:82)
> Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Can't find latest update for ICERAVEN.
> 	at de.marmaro.krt.ffupdater.storage.MetadataCache.getCachedOrFetchIfOutdated(Unknown Source:246)
> 	at de.marmaro.krt.ffupdater.storage.MetadataCache$getCachedOrFetchIfOutdated$1.invokeSuspend(Unknown Source:12)
> 	... 3 more
> Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Can't find latest update for Iceraven.
> 	at de.marmaro.krt.ffupdater.app.impl.AppBase.findAppUpdateStatus(SourceFile:164)
> 	at de.marmaro.krt.ffupdater.app.impl.AppBase$findAppUpdateStatus$1.invokeSuspend(Unknown Source:12)
> 	... 3 more
> Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Fail to request the latest version of iceraven-browser from GitHub.
> 	at de.marmaro.krt.ffupdater.network.github.GithubConsumer.getLatestRelease(SourceFile:136)
> 	at de.marmaro.krt.ffupdater.network.github.GithubConsumer.access$getLatestRelease(Unknown Source:0)
> 	at de.marmaro.krt.ffupdater.network.github.GithubConsumer$getLatestRelease$1.invokeSuspend(Unknown Source:12)
> 	... 3 more
> Caused by: de.marmaro.krt.ffupdater.network.exceptions.NetworkException: Request of HTTP-API https://api.github.com/repos/fork-maintainers/iceraven-browser/releases/latest failed.
> 	at de.marmaro.krt.ffupdater.network.FileDownloader$downloadSmallFileAsync$2.invokeSuspend(SourceFile:92)
> 	at z3.a.resumeWith(Unknown Source:8)
> 	at l4.l0.run(Unknown Source:100)
> 	at p4.e.run(Unknown Source:11)
> 	at r4.j.run(Unknown Source:2)
> 	... 1 more
> Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
> 	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
> 	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
> 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
> 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
> 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
> 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
> 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
> 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)
> 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
> 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
> 	at z4.f.g(SourceFile:94)
> 	at z4.f.c(SourceFile:20)
> 	at z4.d.a(SourceFile:61)
> 	at z4.a.intercept(SourceFile:64)
> 	at a5.f.a(SourceFile:144)
> 	at x4.a.intercept(SourceFile:164)
> 	at a5.f.a(SourceFile:144)
> 	at a5.a.intercept(SourceFile:140)
> 	at a5.f.a(SourceFile:144)
> 	at a5.h.intercept(SourceFile:155)
> 	at a5.f.a(SourceFile:144)
> 	at z4.e.f(SourceFile:97)
> 	at z4.e$a.run(SourceFile:36)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 	at java.lang.Thread.run(Thread.java:920)
> Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
> 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:656)
> 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:615)
> 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505)
> 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425)
> 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:353)
> 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
> 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
> 	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
> 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:255)
> 	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
> 	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
> 	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
> 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
> 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
> 	... 23 more
> Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
> 	... 37 more
> ```
> 
> Device information:
> Key 	Value
> FFUpdater version 	77.6.3 (125) release
> Device 	Moto X4 (lineage_payton, payton, SDM660)
> Manufacturer 	motorola (Motorola)
> Supported ABIs 	arm64-v8a, armeabi-v7a, armeabi
> Android version 	12 (SDK: 32)
> OS 	86a99d2930d3, root, release-keys, 1672118073000

@7sillyeaters

**Comment by Tobi823** [comment]
I move your bug to a new ticket

**Comment by Tobi823** [comment]
I can't reproduce the bug. I looks like that the problem is your smartphone (because trust anchor for HTTPS to connect to api.github.com is missing).

Do you use some Machine-in-the-Middle software? Some VPN apps? Apps that intercept the network traffic?

**Comment by 7sillyeaters** [comment]
I am not aware of any software like that on this phone, no vpn or other apps that may restrict network traffic, however could it have anything to do with the fact that when I connect to WiFi I get a message saying that it's a limited connection and some apps may not work correctly? Maybe there is some app or setting that I am not aware.

Thank you!

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by Tobi823** [comment]
How often does this error occur? Regularly? Only this one time? Every week?

**Comment by 7sillyeaters** [comment]
It just started happening, and happens at least once a day, but I realize now that it started right about the time that I turned the data saver on. Yesterday I turned the data saver off to see if it still happens.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by Tobi823** [comment]
(For me: https://source.android.com/docs/core/data/data-saver)

Strange, the data saver should not caused the CertPathValidatorException.

But the documentation says

> Conversely, to work well with Data Saver, apps should not: ... Download updates

Maybe the operating system penalizes FFUpdater because it downloads updates even though the data saver is turned on?

**Comment by Tobi823** [comment]
TODO for me: FFUpdater should not download updates in the background when the data saver is turned on

**Comment by 7sillyeaters** [comment]
After turning the data saver off, I think I only got the error once or twice. It's been several days now and I'm getting it way less than before.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by TPS** [comment]
@Tobi823 Data saver should only matter to FfU when on mobile/limited data.  Else, on typical wifi or unlimited mobile data, like Android, FfU should _ignore_ Data Saver state.  (E.g., mine is always on, but only in effect on data when the OS is aware that connection is limited.)

**Comment by 7sillyeaters** [comment]
When I connect to my home Wifi network, my phone always says "Limited connection." I tried to figure out why this is, because no other devices say that, including an Amazon Fire tablet with Lineage OS on it. I found an article telling how to fix it, but none of the suggestions worked. As far as I can tell for general using, it connects fine, and everything I use works. It must somehow be background stuff that is affected.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by TPS** [comment]
@7sillyeaters Which Android do you run?

**Comment by 7sillyeaters** [comment]
Android 12 with Lineage 19 (payton).

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by TPS** [comment]
@7sillyeaters I'm trying very hard to understand, so forgive me if I ask the very obvious:

<Details>

<Summary>

Are you saying you don't have this option when you go into your wifi connection's parameters?

</Summary>

![Screenshot_2023-02-12-21-46-06-50_llcrop.png](https://user-images.githubusercontent.com/185902/218360335-5d5e4055-24cc-4e8c-b4c8-ec05b0b3f8df.png)

</Details>

**Comment by 7sillyeaters** [comment]
I have those options, (unmetered is selected)what I'm talking about is this. (Sorry it's so huge.)

[Screenshot_20230213-062245_Trebuchet.png]

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by TPS** [comment]
I don't see the pic, but it shouldn't matter.  Setting the connection to "unmetered" tells Android to ignore Data Saver for that connection, so I think the error must lie elsewhere.  Maybe your ROM handles that logic in a nonstandard way with your hardware?

**Comment by 7sillyeaters** [comment]
The picture was just showing that in my wifi settings, where it shows my wifi connection, it always says "Limited Connectiom." My home wifi connection is named "dd-wrt 2.4G". So it reads like this:

> WiFi (checkbox on)
>
> dd-wrt 2.4G
> Limited connection/Unmetered

I don't know why it always shows it has a limited connection, because everything (with possibly the exception of this fFupdater error, if this is the cause) works fine.

Reidun

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by TPS** [comment]
Does it still show Limited Connection when Data Saver is off?

**Comment by TPS** [comment]
Also, per https://wiki.lineageos.org/devices/payton/, this is no longer the most updated version of the OS for your hardware.  Does a newer/older version exhibit the same?  I'm very much thinking it's a ROM vs hardware incompatibility that manifesting this way, but the 2 weird things (Limited Connection, FfU problem) may not be directly related to each other, but to that.

**Comment by 7sillyeaters** [comment]
Yes, data saver doesn't affect that.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by 7sillyeaters** [comment]
Thank you, yes, there is an update to the system, but I haven't installed it yet because it's not just a simple install via the installer. Maybe now this will give me the motivation to get it done and see if this error goes away.

Thanks!

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by Tobi823** [comment]
The next FFUpdater version will not download updates in the background when the data saver is enabled.
