### ISSUE TITLE
77.7.3 Self Update Loops

### ISSUE THREAD

**Issue by dreamsyntax** [Tobi823/ffupdater#335]
77.7.3 continuously sees itself as an update after 77.7.2 > 77.7.3.

App reset loops most opens, when it does get through you can see the update is still detected. No crashlog.

![Screenshot_20230204-103725.png](https://user-images.githubusercontent.com/14857235/216781670-dfa4905e-5286-4f85-a684-41ea4bc2294f.png)

**Comment by dreamsyntax** [comment]
Wiping application data "Clear Storage" in system settings resolves this issue.

**Comment by Tobi823** [comment]
I also encounter this problem (ui shows wrong values after an app update) but I was not able to fix if

You could also fixed the bug by manual refreshing/searching for updates in the app

**Comment by Tobi823** [comment]
Maybe I fixed the issue - I guess that there was a timing problem. The info about the latest available version was stored asynchronous. But the check (if an update is available and if the download arrow should be red) was done immanently after the info was stored asynchronous.

**Comment by Tobi823** [comment]
Version 77.7.4 with the fixed is now released.
