### ISSUE TITLE
Add support for DroidChrome browser

### ISSUE THREAD

**Issue by trickyburst** [Tobi823/ffupdater#338]
[DroidChrome by Marmaduke](https://github.com/macchrome/droidchrome/releases) is a Chromium fork with [Bromite](https://github.com/bromite/bromite) patches applied, adding additional ad blocking capabilities

It's listed on https://chromium.woolyss.com/#android as `Marmaduke` `ungoogled` `all-codecs` `android64`

**Comment by Tobi823** [comment]
I'm currently busy but I will think about it

**Comment by SkewedZeppelin** [comment]
https://github.com/bromite/bromite/issues/2564#issuecomment-1435942500

They are likely violating GPL-3.0 license.
