### ISSUE TITLE
Nit: Unnecessary Scrolling

### ISSUE THREAD

**Issue by TPS** [Tobi823/ffupdater#339]
_N.B.: This is a_ **very** _minor nit & certainly not worth even being called a bug.  I happened to run into it in process of posting https://github.com/Tobi823/ffupdater/issues/9#issuecomment-1427020834 & thought you might be interested… when bored. 😅_

<Details>

<Summary>

When trying to make the following screenshot,

</Summary>

![FfU 0 Home.18Direct.png](https://user-images.githubusercontent.com/185902/218313098-b09934a6-06b2-4101-8238-8d65028de66d.png)

</Details>

<Details>

<Summary>

I ended up with this monstrosity

</Summary>

![FfU 2b Combined Scrolled.18Direct.png](https://user-images.githubusercontent.com/185902/218312446-4f8878a0-301f-4fdb-8673-7635791c27e1.png)

</Details>

<Details>

<Summary>

because FFU allows very unnecessary scrolling (compare blank space toward bottom of the 1st screenshot) to this position

</Summary>

![FfU 2a Scrolled.18Direct.png](https://user-images.githubusercontent.com/185902/218312657-7aa7331d-1ad8-4968-8488-49a05ef60a36.png)

</Details>

which completely confuses Android's new scrolling screenshot feature & leads to the 2nd image.

See?   Completely unimportant,  but  might lead to some confusion when we non-devs post bug report screenshots w/o proofreading them 1st.

As always, thanks for everything, including putting up w/ us, @Tobi823. 🙇🏾‍♂️

**Comment by Tobi823** [comment]
I can't reproduce this bug. When I try to make an extended screenshot on my Pixel 3a, I get an image with all apps, without any glitches and without the upper blue box with the "FFUpdater" text.
