### ISSUE TITLE
Session Installer shows dialog despite me using android 12

### ISSUE THREAD

**Issue by LeSnake04** [Tobi823/ffupdater#348]
The Installer description says on Android 12, no confirmation dialog is needed. Do I need to give extra permission to allow the App to not show the dialog or should it show none out of the box?  

Device: Fairphone 4
OS: Android 12
Rooted: Yes (root installer broken, #346 )

**Comment by Tobi823** [comment]
With the session installer you have to confirm only once. The next update will be updated silently in the background. This is a limitation of Android. (But I think this is a good compromise of security and convenient).
Maybe I should improve the description of the session installer.
