### ISSUE TITLE
No longer fetches updates for Firefox Beta

### ISSUE THREAD

**Issue by RogerioTDS** [Tobi823/ffupdater#352]
FFupdater version 77.7.6
It no longer shows updates for Firefox Beta.
The latest version available from FFupdater is version 110.0b6, dated February 3rd.
I had to install version 111 available on the play store.
![Screenshot_20230225-144908_FFUpdater](https://user-images.githubusercontent.com/120617835/221371995-7b1e0712-f911-4a70-ab2a-b1e2f3c3c142.png)

**Comment by Tobi823** [comment]
Should be fixed in 77.7.8
