### ISSUE TITLE
DO NOT INSTALL THE KIWI BROWSER

### ISSUE THREAD

**Issue by Tobi823** [Tobi823/ffupdater#36]
https://github.com/Tobi823/ffupdater/issues/35

**Comment by Tobi823** [comment]
Answer from the Kiwi developer:

> It's actually quite simple, Kiwi earns money for every search it forwards to Yahoo or Microsoft Bing.

It seems that the developers have to forward search requests to their servers and then to the search engine in order to get paid by the search engine.

> The parameters and integration method are defined by the search engines themselves, we don't have our words at all how the integration is done.

> They [Yahoo or Microsoft Bing] have a standard guide on how to integrate, either you follow this guide, or you don't work with them.

I guess it's fine. Although i don't like it, i understand that the money for the app development has to come from somewhere (even Firefox is paid to use "Google" as the default search engine).

But I think that Kiwi should not be managed by FFUpdater because this browser has additional usability features and no additional privacy features. FFUpdater is about privacy and not usability.

**Comment by Coool** [comment]
Kiwi Browser has been updated recently to [137.0.7337.0](https://github.com/kiwibrowser/src.next/releases/tag/14310011181) version

Related:
- #621
- #468
- #121
- #36
- #35
- #22
