### ISSUE TITLE
It does not match the latest version of Firefox

### ISSUE THREAD

**Issue by longmoon77** [Tobi823/ffupdater#364]
Google Play Store

![Screenshot_2023-03-06-04-03-49-919_com.android.vending.jpg](https://user-images.githubusercontent.com/62339707/222983540-125765e6-dad5-4db9-85f8-3b778830fbe5.jpg)

FFupdater

![Screenshot_2023-03-06-04-05-31-503_de.marmaro.krt.ffupdater.jpg](https://user-images.githubusercontent.com/62339707/222983541-59a5a8d7-2e29-4675-a3cd-7736118cea99.jpg)

Github

![Screenshot_2023-03-06-04-12-43-722_com.github.android.jpg](https://user-images.githubusercontent.com/62339707/222983539-e012c1bb-6292-4e92-a1d5-acb494f84b89.jpg)

**Comment by welkinpc-91** [comment]
If this info is any use to Tobi823, they changed the url for the apks.

They changed the pathcto

/tasks/index/mobile.v3.firefox-android.apks.fenix-release.latest

**Comment by Tobi823** [comment]
Thanks for the info @welkinpc-91 - but I'm using the Focus/Klar version from GitHub (https://github.com/mozilla-mobile/firefox-android) and not from their CI website.

@longmoon77 The current version for Focus is 110.1.0 (see https://github.com/mozilla-mobile/firefox-android/releases/latest and  https://www.apkmirror.com/apk/mozilla/firefox-focus-private-browser)

I suspect that the maintainers of https://github.com/mozilla-mobile/firefox-android accidentally released an update with a wrong version (or a beta update as a normal update). And this temporary version was installed by FFUpdater on your phone.

As far as I know there is no bug in FFUpdater. I guess you have to wait for the release of the real 111.0 version of Firefox Focus.

**Comment by welkinpc-91** [comment]
> Thanks for the info @welkinpc-91 - but I'm using the Focus/Klar version from GitHub (https://github.com/mozilla-mobile/firefox-android) and not from their CI website.

Thanks for the clarification but this leads me to a question, why does ffupdater sometimes lead me to their CI website?
Is this a bug when having a language other than english? (Dunno what it has to do with anything but it's the only setting I changed because It is my native language)

![Screenshot_20230307-224251_FFUpdater.jpg](https://user-images.githubusercontent.com/124310619/223560002-e16eda31-2b1c-4555-aa23-5ebda42c4e81.jpg)

**Comment by Tobi823** [comment]
Oh sorry - I confused your issue with another

**Comment by Tobi823** [comment]
I think the real solution is to download the APK from GitHub. The Mozilla CI seems to be less reliable for downloading the latest Firefox release

**Comment by Tobi823** [comment]
TODO: I have to improve the caching because multiple apps will use the same API for update checking

**Comment by Tobi823** [comment]
Should be fixed in 77.7.12
