### ISSUE TITLE
Firefox not Updating

### ISSUE THREAD

**Issue by Cheechoz** [Tobi823/ffupdater#369]
It still says 110.0.1 as the latest build.  I manually updated to 110.1.0 and today updated to 111.0.  It is also telling me to update, but to 110.0.1 from last month.

**Comment by dypa** [comment]
@Tobi823 It looks like the url has changed from https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.release.latest to https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v3.firefox-android.apks.fenix-release.latest

**Comment by bryce-lynch** [comment]
Same here, I have FF 110.1.0 installed but it wants to install 110.0.1 (with 111.0 [available from the official git](https://github.com/mozilla-mobile/firefox-android/releases/tag/fenix-v111.0))

**Comment by Tobi823** [comment]
@dypa Thanks for the info. I already discovered the url but I was not sure if the real Firefox or just a test version is published

**Comment by Tobi823** [comment]
Should be fixed in 77.7.12

**Comment by Attigliuzzo** [comment]
> Should be fixed in 77.7.12

Now it Is available the 111.1.0 version of Firefox, i downloaded It from [https://ftp.mozilla.org/pub/fenix/releases/](url)
The app doesn't show this update.

**Comment by Attigliuzzo** [comment]
> Should be fixed in 77.7.12

Now it Is available the 111.1.0 version of Firefox, i downloaded It from [https://ftp.mozilla.org/pub/fenix/releases/](url)
The app doesn't show this update.

**Comment by Tobi823** [comment]
The download url for Firefox Release changed again :(
