### ISSUE TITLE
Limit Chromium background updates to only once a day

### ISSUE THREAD

**Issue by Tobi823** [Tobi823/ffupdater#388]
On https://storage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Android_Arm64/ every two hours a new version of Chromium will be released.

But updating Chromium up to 12 times a day is in my opinion pointless. I should limit the automatic background update to only once a day.

FYI @DxBONESxBACK

**Comment by DxBONESxBACK** [comment]
Okay thank you.
