### ISSUE TITLE
Bromite webview

### ISSUE THREAD

**Issue by linsui** [Tobi823/ffupdater#39]
Could you please add bromite webview? Thanks!

**Comment by Tobi823** [comment]
Yes, I can.
But I'm currently busy - I think I'll need two weeks for that.

**Comment by linsui** [comment]
Thanks!

**Comment by linsui** [comment]
Yes. Just download and install if it has been installed.

**Comment by chrislogan-foss** [comment]
I thought that Bromite WebView doesn't work unless your device is rooted or will it only work with Bromite unless you have root installed

**Comment by linsui** [comment]
Yes, you need root to install it because it needs to replace the system webview.

**Comment by Nickoriginal** [comment]
Now it doesn't!
https://www.bromite.org/news/2022-02-05-bromite-webview-package-name-change

**Comment by Tobi823** [comment]
I've just added the support for Bromite SystemWebView to FFUpdater. If you want to try it out now
[ffupdater-release.zip](https://github.com/Tobi823/ffupdater/files/8506460/ffupdater-release.zip)

**Comment by Tobi823** [comment]
And I've just seen that Bromite supports auto-updating itself https://www.bromite.org/news/2021-10-16-bromite-v94-released-with-auto-update-feature. 

But makes it sense to keep Bromite in FFUpdater? 

In my opinion it only makes sense if FFUpdater offers something that Bromite cannot. Maybe it's time to finish the silent background update feature with the Android12-API or root
