### ISSUE TITLE
Bromite EOL/abandoned?

### ISSUE THREAD

**Issue by automorphism88** [Tobi823/ffupdater#396]
I noticed the most recent version of Bromite (both in FFUpdater and on their GitHub page) is 108.x, and was released in December 2022. I believe that is EOL, and 112 is the current stable version of Chromium. Their GitHub doesn't officially say it's no longer being maintained, but that's what it looks like (https://github.com/bromite/bromite/issues/2610). Doesn't this merit moving it to the EOL category like Ungoogled Chromium? Also, it would be nice if FFUpdater warned existing users, since it's really not safe to continue using a browser that isn't getting security updates.

**Comment by PF4Public** [comment]
> EOL category like Ungoogled Chromium?

Excuse me for interjecting, but how is Ungoogled Chromium EOL?

**Comment by Tobi823** [comment]
> Doesn't this merit moving it to the EOL category like Ungoogled Chromium?

Yes it does. But the last days I was busy writing my master thesis.

**Comment by TheyEatFood** [comment]
Yeah! I used to use it a ton. Sad to see it no longer being maintained...

**Comment by welkinpc-91** [comment]
One of their devs/contributors is still maintaning a more up to date beta version (with the Chromium branding, but with all the bromite patches and more), but that's about it.
The owner/main dev just said nothing has been abandoned only to ghost for three more months.

**Comment by paritosh9199** [comment]
> One of their devs/contributors is still maintaning a more up to date beta version (with the Chromium branding, but with all the bromite patches and more), but that's about it.
> The owner/main dev just said nothing has been abandoned only to ghost for three more months.

Can you share the repo link?

**Comment by welkinpc-91** [comment]
> Can you share the repo link?

[uazo/bromite-buildtools](https://github.com/uazo/bromite-buildtools)

They only build for 64-bit devices and a Windows version, they also aren't sure about the future of the repo itself when I asked if they could give permission to add to FFUpdater.
So download with caution/with that knowledge.
Find another backup browser just to be on the safe side, in case the Bromite project dies for good.
Still, minor bug aside it works very good for a Beta, if you want to keep using Bromite.

**Comment by Tobi823** [comment]
I removed Bromite and Bromite SystemWebView from FFUpdater. If the developers restart the project I will add the browsers again.
