### ISSUE TITLE
handle background update more gracefully when the browser is being used

### ISSUE THREAD

**Issue by gigglylo** [Tobi823/ffupdater#400]
I use iceraven, and it updates very frequently lately. 

So, I just used this browser and it closed abruptly, checked my notification and it said my browser has been updated. 

It would be nice if ffupdater doesn't just update my browser while in use. Probably check if the browser in question running before installation, notify the user new version is ready to install when the screen is on, or just update when the screen is off (with no download/media playing)

**Comment by Tobi823** [comment]
To my knowledge this is currently not possible. Only in Android 14 (not yet released) this would be possible.

**Comment by Tobi823** [comment]
https://developer.android.com/reference/android/content/pm/PackageInstaller.InstallConstraints

**Comment by Tobi823** [comment]
> Google has significantly restricted access to /proc in Android Nougat. To get a list of running processes on Android Nougat you will need to use UsageStatsManager or have root access. https://stackoverflow.com/a/32366476

Maybe it could be possible with UsageStatsManager. But I have to look into it how reliable this method is.

**Comment by L31FY** [comment]
Firefox Nightly can also be really bad about this behavior due to very frequent updates on the number of multiple a day usually. The "update check only if the device is idle" setting stopped most instances of this doing that in my case though I'd say and so I would suggest maybe trying that setting and see if there's any improvement.

**Comment by TPS** [comment]
> https://developer.android.com/reference/android/content/pm/PackageInstaller.InstallConstraints

@Tobi823 Maybe close #344 in favor of this, since all the reports are here?

**Comment by Tobi823** [comment]
* add option to install updates if the device is non interactive (screen == off)
