### ISSUE TITLE
visual error by downloading updates

### ISSUE THREAD

**Issue by makuru-dd** [Tobi823/ffupdater#401]
Hello

This error was shown for me when I updated the Tor browser because i think there was no file size metadata attached or the download hasn't started yet, i would suggest changing it from "()" as shown in image below, to "(NaN %)"; "NaN" or "(% not Available.)".
![IMG_20230422_134154](https://user-images.githubusercontent.com/58048293/233783138-80779696-1098-4e1b-abc2-f8014662be9c.jpg)

**Comment by Tobi823** [comment]
You are right - the empty brackets look awful. But I think that many users will not understand ``NaN``. I will simply hide the brackets if the download hasn't been started.
