### ISSUE TITLE
FFUpdater cannot be updated due to wrong certificate

### ISSUE THREAD

**Issue by seniordevel** [Tobi823/ffupdater#402]
Hello, I installed FFUpdater from f-droids repository. So far everything works fine, but this app won't  update itself.

Is this behaviour intended?

![Screenshot_20230424-124728](https://user-images.githubusercontent.com/129897917/233976504-44fd04ed-8ac1-43a4-ac85-df6a8f3527f8.png)

**Comment by Tobi823** [comment]
This is intended: If the user installs FFUpdater with F-Droid I suspect that the user also wants to update it with F-Droid.

Actually i wanted to adjust this error text, but i didn't manage it yet because of university work.

**Comment by seniordevel** [comment]
Thank you for your fast reply, please allow one more question, before I will close this issue.

Would FFUpdater update itself, if installed from here (Github) ?

**Comment by Tobi823** [comment]
> Would FFUpdater update itself, if installed from here (Github) ?

Yes
