### ISSUE TITLE
Publish ffupdater to google play

### ISSUE THREAD

**Issue by soredake** [Tobi823/ffupdater#403]
It would be nice if ffupdater is available in google play.

**Comment by Tobi823** [comment]
TLDR: I am against publishing FFUpdater on Google Play Store:

Arguments for uploading:
- for some users more convenient / accessible

Arguments against uploading:
- most of the browsers can be installed/downloaded from Google Play Store directly
- I don't know the rules of Google Play Store
- additional work for setting up + using the Google Play Store account
- IMHO F-Droid + Download from Github/Gitlab are sufficient choice

I want to invest my time where it will help the most users.
