### ISSUE TITLE
Improve detection of aggressive battery optimization (killing the background job)

### ISSUE THREAD

**Issue by soredake** [Tobi823/ffupdater#409]
All phones come with certain battery optimizations, for me ffupdater for example is not updated anything in background until i manually disabled battery optimizations.

https://developer.android.com/reference/android/provider/Settings#ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS
https://dontkillmyapp.com/

**Comment by Tobi823** [comment]
The joy of developing Android apps (for the usual suspects Samsung, Huawei, ...) 😄

**Comment by Tobi823** [comment]
> On Android 11 Samsung will prevent apps work in background by default unless you exclude apps from battery optimizations.

Why?

**Comment by Tobi823** [comment]
Done

**Comment by soredake** [comment]
This should be done even in aosp-like as they have battery optimizations too like all android

**Comment by Tobi823** [comment]
But not all battery optimizations are bad. The important thing is that the background job is regularly called - but the exact timing is not relevant.

But you make me think. Maintaining a list of problematic manufacturer is not a good idea. FFUpdater should check if the background was executed in the last 24h or (update check interval in hours * 4). 

If not, then show an error notification + request the removal of battery optimization.

**Comment by Tobi823** [comment]
Done
