### ISSUE TITLE
[Suggest] New Browser: Thorium

### ISSUE THREAD

**Issue by kowith337** [Tobi823/ffupdater#414]
Future use {[More info](https://github.com/Alex313031/Thorium-Special/releases/tag/migrate)}: https://github.com/Alex313031/thorium-android/releases
> Former repo: https://github.com/Alex313031/Thorium-Special/releases

Note:
- All Android builds will be titled in releases title.
- This maybe push into "Better than Chrome" section due to...
  - Out-of-box settings about Auto sign-in, password manager, payment method, help improving, suggested, etc. are enabled by default
  - certain features are leftover but not fully functional, e.g. NTP news feed like Chrome but not fully work in Chromium and same as this.

**Comment by brian6932** [comment]
@kowith337 please edit your post to reflect the repo name changes:
https://github.com/Alex313031/Thorium-Special/releases

**Comment by kowith337** [comment]
Sorry for bumb, now I see the releases are start with 115 at new repository now...

**Comment by chris122380** [comment]
Any news on getting this added to FFupdater?

**Comment by Tobi823** [comment]
@chris122380 Do you watch  Chris Titus Tech too? (Because the timing is perfect 😄 )

**Comment by chris122380** [comment]
> @chris122380 Do you watch Chris Titus Tech too? (Because the timing is perfect 😄 )

Yes, I've also looked at this before the only thing I wish the browser had is ad blocking. I'm using Cromite but I'm waiting for the password autofill problem to be fixed on that one.

**Comment by Tobi823** [comment]
Done
