### ISSUE TITLE
auto download in the background

### ISSUE THREAD

**Issue by TitanNano** [Tobi823/ffupdater#42]
Could we get an option to let the app automatically download updates? 
So when I click the notification it just has to install the app and I don't have to wait for it to be downloaded.

**Comment by Tobi823** [comment]
It's already implemented in version "72.1.0" - but maybe it does not work on your phone.

If you phone has enough free space (> 200MB), FFUpdater will download the update in the background. When the download is complete, the update notification is displayed.

When you apply the app update, you will see the notice "Use already downloaded file from" (see screenshot)

![Screenshot_1620577261](https://user-images.githubusercontent.com/10066140/117579731-7bc5c700-b0f4-11eb-9f22-5d434e31a4c0.jpg)

Can you double check if this works on your device?

**Comment by TitanNano** [comment]
@Tobi823 ah I see, I looked at the change log but couldn't find anything. Unfortunately I'm hitting #40 but I will let you know once the new F-Droid build is out.
