### ISSUE TITLE
Firefox Nightly listed twice on main screen

### ISSUE THREAD

**Issue by bilemke** [Tobi823/ffupdater#435]
**Describe the bug**
With Firefox Nightly installed, the main screen shows two entries for it. One in typical location in lust. The other at the very top of the list. 

**To Reproduce**
1. Have Firefix Nightly installed.
2. Open FFUpdater

**Expected behavior**
Firefox Nightly listed only once.

**Error message from FFUpdater**
No error message. Only erroneous display/functionality.

**Comment by bilemke** [comment]
Validated above on 3 devices. Galaxy S23 Ultra, Galaxy S10, and Surface Duo. First being Android 13, later 2 being Android 12. Cleared FFUpdater data and reinstalled it. Also removed Firefilox Nightly and reinstalled it.

**Comment by Tobi823** [comment]
Fixed in 78.0.3
