### ISSUE TITLE
Add Cromite 

### ISSUE THREAD

**Issue by Tobi823** [Tobi823/ffupdater#447]
https://github.com/uazo/cromite

https://github.com/Tobi823/ffupdater/discussions/446

**Comment by blacklightpy** [comment]
*Cromite

**Comment by Tobi823** [comment]
Thanks

**Comment by hank-tu-biz** [comment]
Why closed? There's an asset available. Is it being considered?

**Comment by hank-tu-biz** [comment]
Got it. Apologies. I'm a complete noob to GitHub. I did find the right thread and it had adequate comments. I did just download Cromite and set it up. Seems fine so far to this neophyte.

Sep 11, 2023 11:27:01 Tobias Hellmann ***@***.***>:

**Comment by Tobi823** [comment]
Done
