### ISSUE TITLE
Option to disable an installed browser's updating

### ISSUE THREAD

**Issue by brian6932** [Tobi823/ffupdater#461]
**Is your feature request related to a problem? Please describe.**
You may want to install and update from a different source, or may be having some issues updating a specific browser.

**Describe the solution you'd like**
In these cases, a blocklist-like feature for browsers in the client seems necessary.

**Comment by marcdw1289** [comment]
In FFUpdater's settings you will find "Exclude apps from update check"

That sounds like what you are looking for?
![Image8687294161082775223](https://github.com/Tobi823/ffupdater/assets/42319182/e986e2bd-d53c-4c36-b3d0-bf467aa495e1)

**Comment by brian6932** [comment]
Oh my bad, I completely missed this 😓

**Comment by Tobi823** [comment]
@marcdw1289 Thanks for your quick reply

@brian6932 
> Small suggestion, maybe there should be a way to do it from the main screen, some type of icon or dropdown.

good idea

I created the issue #465 as a reminder for me
