### ISSUE TITLE
Kiwi: Parse the release description to extract the version name

### ISSUE THREAD

**Issue by MrHappy** [Tobi823/ffupdater#470]
**Describe the bug**
Installed version (at this moment) is: 116.0.xxxxxx
Available version is: 5751242426.
This is shown directly after installation.

**To Reproduce**
Install Kiwi browser (through FFUpdater)

**Expected behavior**
Show the same (format of) versionnumber

**Comment by Tobi823** [comment]
Nevermind - I could extract the version name from the textual description of every release

**Comment by Tobi823** [comment]
Done
