### ISSUE TITLE
Brave should use Bravearm64Universal.apk instead of BraveMonoarm64.apk 

### ISSUE THREAD

**Issue by Retold3202** [Tobi823/ffupdater#475]
**Is your feature request related to a problem? Please describe.**
Installing Brave from FFUpdater on certain 64-bit devices like the new Google Pixels results in the app not functioning and crashing on launch.

**Describe the solution you'd like**
I propose that FFUpdater should download Bravearm64Universal.apk where applicable instead of trying to download BraveMonoarm64.apk like it currently does, as Bravearm64Universal.apk isn't broken and functions perfectly on these devices, tested on my Pixel 7 Pro.

**Comment by chris122380** [comment]
This would also solve the issues found in 
#232 and #293

**Comment by Sepero** [comment]
How did a mistake like this even happen? Of course it should be using the Universal apk

**Comment by chris122380** [comment]
> How did a mistake like this even happen? Of course it should be using the Universal apk

I used to download Brave directly from GitHub and I didn't realize there was a universal APK. Then when I started digging I realized there's a whole lot more listed under the release downloads then I realized. I'll be manually grabbing the universal until this fix is applied.

**Comment by Tobi823** [comment]
@Retold3202 Thanks for the info. Issue is now fixed and will be released in 78.1.5.

**Comment by Tobi823** [comment]
@Sepero I know you didn't mean that but the GitHub community is global. You should be careful in your choice of words to prevent misunderstandings (see how different some cultures work https://www.businessinsider.com/the-culture-map-8-scales-for-work-2015-1?op=1). One could understand _"How did a mistake like this even happen?"_ as _"How did a mistake like this even happen? Are you stupid?"_

And for your info, why this happened: There was no Bravearm64Universal.apk when I added Brave to FFUpdater.

**Comment by Sepero** [comment]
Sorry @Tobi823. I'll admit that I was a upset to discover that the Universal apk wasn't being used. Though I never meant to shame you or your work. It's true, the internet is global, so I'm glad you can understand it from my side as well. A good rule to follow is remarks on software should never, Never be taken personally.

I'm massively thankful for FFUpdater and your dedication to it. You are a good champion for many people.
