### ISSUE TITLE
Upgrade FFUpdater's UI to Material3 (Material you)

### ISSUE THREAD

**Issue by TeaOwO** [Tobi823/ffupdater#479]
To me ffupdater's UI seems stale and outdated, 
So updating it would be great! I think that using Google's material 3 design language would make it look really good, dynamic colouring could also add a really nice touch! 

hopefully you'll at least take my request into consideration, Thanks for the great app. <3

**Comment by Tobi823** [comment]
> To me ffupdater's UI seems stale and outdated,

I agree, but fixing bugs has a higher priority. I will look later into it

**Comment by TeaEndsAcronyms** [comment]
> As a hater of the material so-called "design", I would rather suggest classical/3D/Aero design, which corresponds to Symbian, first Android versions, Windows Vista/7, and the 2005-2012 era.

Fix an outdated design with an even more outdated design? (No offense, but I would much prefer MD3 as it looks quite modern + I don't code but I'd assume that it would be easier, since it's going from MD2 to MD3)

**Comment by Tobi823** [comment]
FYI I finish my study of computer science and I'm now working as a software engineer. Sadly I don't have the time to fix all issues. 

Therefore I have to prioritize. Fixing bugs and implementing important features (like a new browser) are (in my humble opinion) more important that the UI.

And I dont think that UI must be that pretty. If everything works, the UI must only be used on the first run. After that, FFUpdater should update everything in the background.

**Comment by TeaOwO** [comment]
> FYI I finish my study of computer science and I'm now working as a software engineer. Sadly I don't have the time to fix all issues. 
> 
> Therefore I have to prioritize. Fixing bugs and implementing important features (like a new browser) are (in my humble opinion) more important that the UI.
> 
> And I dont think that UI must be that pretty. If everything works, the UI must only be used on the first run. After that, FFUpdater should update everything in the background.
> 
> 

it's fine <3, will be closing the issue now!
