### ISSUE TITLE
Autoupdate not working

### ISSUE THREAD

**Issue by pistolius** [Tobi823/ffupdater#483]
**Describe the bug**
App does not autoinstall new Firefox Nightly despite setting + session installer, and instead prompts user to install via a notification.

**To Reproduce**
Wait for update to come. Pixel 6 Pro running Android 14 Beta 5.1

**Expected behavior**
After first manual installation the app should background install as per setting description.

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:
No error log

**Comment by Tobi823** [comment]
Can you open FFUpdater, click on the info-icon in the top right corner and tell me the timestamp of the last successful background check?

I wan to make sure that the background update checker was and is executed

**Comment by Tobi823** [comment]
![3](https://github.com/Tobi823/ffupdater/assets/10066140/9c73b4ba-88dc-48f6-976c-deef47600fb4)

**Comment by pistolius** [comment]
![Screenshot_20230823-165350](https://github.com/Tobi823/ffupdater/assets/107413189/53a3d60c-44c8-4826-96b6-b73518c9c86c)

**Comment by pistolius** [comment]
I tried to Email but it didn't go through. That update required me to manually install, as do all the others I have had since updating the app

**Comment by Tobi823** [comment]
I can't reproduce it. Can you text me again if this problem occur again?
