### ISSUE TITLE
Automatic update using root

### ISSUE THREAD

**Issue by gnuhead-chieb** [Tobi823/ffupdater#49]
It can be useful to support automatic update without confirmation dialog using root.

**Comment by Tobi823** [comment]
Unfortunately, I have not yet found the time to look into this topic further.

But there is an interesting development. Android 12 is supposed to support silent updates.
But it will be a long time before most people will have Android 12.

https://www.xda-developers.com/android-12-alternative-app-stores-update-apps-background/

Manifest.permission.UPDATE_PACKAGES_WITHOUT_USER_ACTION https://developer.android.com/reference/android/Manifest.permission#UPDATE_PACKAGES_WITHOUT_USER_ACTION

PackageInstaller.SessionParams#setRequireUserAction(int) https://developer.android.com/reference/android/content/pm/PackageInstaller.SessionParams#setRequireUserAction(int)

**Comment by Tobi823** [comment]
It's now implemented and will be released in the next version.

After too many attempts I managed to root my old flox tablet and test FFUpdater.
The implementation is definitely not trivial. My first attempts did not work.
But luckily I was able to use the source code from AuroraStore.
