### ISSUE TITLE
Add cromite. A fork of bromite.

### ISSUE THREAD

**Issue by OkeyF** [Tobi823/ffupdater#490]
been using "cromite" for a few days now. it has its own adblock filters that aren't to bad , but just lacks extension support.. I feel at home again finally since I'm sure bromite Is dead. I'm pretty sure the guy who made it was part of the bromite project at some point.

**Comment by Tobi823** [comment]
Adding Cromite is on my bucket list

**Comment by Tobi823** [comment]
Dupliate of  #447
