### ISSUE TITLE
New version has incorrect version

### ISSUE THREAD

**Issue by Daviteusz** [Tobi823/ffupdater#497]
**Describe the bug**
New version 78.1.7 has incorrect version 78.1.6 and if you update it in ffupdater, it still shows version 78.1.6.

**To Reproduce**
1. Download 78.1.7 and install
2. Check app info version.

**Expected behavior**
New version should have different version 😂

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:

**Comment by chris122380** [comment]
I am also seeing this same issue. After the install under the app info for the operating system It also shows 78.1.7 as 78.1.6.

Oxygen OS 13
OnePlus 9 Pro

**Comment by brian6932** [comment]
Can reproduce

**Comment by Tobi823** [comment]
I have the same issue ;)

I will look into it tomorrow. I'm currently not on my computer

**Comment by Tobi823** [comment]
Very strange. Ffupdater from my repository has the right version.

Maybe my script has uploaded a wrong version to GitHub.

**Comment by il-santo** [comment]
Same issue for me.

**Comment by Tobi823** [comment]
Should be fixed now. I replace the APK file from the Github release with the correct APK file.

**Comment by il-santo** [comment]
Yes, now it's ok. Thanks!
