### ISSUE TITLE
Installed new version

### ISSUE THREAD

**Issue by mcbelisle** [Tobi823/ffupdater#498]
The new episode link is same as old

*Describe the bug**

**To Reproduce**

**Expected behavior**

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:

**Comment by Tobi823** [comment]
Should be fixed now. I replace the APK file from the Github release with the correct APK file.

**Comment by mcbelisle** [comment]
When I install the latest version, the previous one gets reinstalled

**Comment by Tobi823** [comment]
Clear the cache of FFUpdater and try again.

**Comment by henrikx** [comment]
Clearing the cache wasn't enough. Had to delete full app data (which for the record was 200 MB, so I think some cleanup of old APKs isn't working).

**Comment by Tobi823** [comment]
Sorry for your trouble. Next time I double check that I update my Gradle cache before I start my release script (which uploads the APK to Github).
