### ISSUE TITLE
Suggestion: Add ungoogled-chromium

### ISSUE THREAD

**Issue by ygz213** [Tobi823/ffupdater#50]
I think [ungoogled-chromium](https://github.com/ungoogled-software/ungoogled-chromium-android) should add to FFUpdater because it is privacy-oriented browser like others.

**Comment by Tobi823** [comment]
Thanks :+1: and thanks for your work supporting privacy-minded people.

Unfortunately, I haven't found the time to expand the app in the last few weeks.
But I think it will be better in the next weeks.

**Comment by Tobi823** [comment]
I finally had time to add the support to FFUpdater. Version 74.5.1 will support the Ungoogled Chromium.

You can either wait for the official F-Droid release, install the APK file from GitHub/GitLab or try my personal F-Droid repository (see https://github.com/Tobi823/ffupdater#f-droid-repository).
