### ISSUE TITLE
"Installer method" is not translatable | Weblate - unused screenshots alert

### ISSUE THREAD

**Issue by Daviteusz** [Tobi823/ffupdater#501]
**Describe the bug**
"Installer method" is not translatable
https://github.com/Tobi823/ffupdater/blob/db68c7cb9281fb344f40340577dfb4c45fa7b60f/ffupdater/src/main/res/xml/root_preferences.xml#L164C2-L164C2
<img src=https://github.com/Tobi823/ffupdater/assets/11527277/6e318ac9-668d-407b-929a-f88d837b68f8 width=30%>

**Expected behavior**
"Installer method" should be translatable

-------------

**Describe the bug**
<img src=https://github.com/Tobi823/ffupdater/assets/11527277/9eb97db5-86b9-41d2-8d95-8656dd21f8c1 width=35%><img src=https://github.com/Tobi823/ffupdater/assets/11527277/60abbf01-7b5a-4c3d-8422-22b9032bb3a0 width=35%>

**To Reproduce**
1. Go to https://hosted.weblate.org/projects/ffupdater/ffupdater-app-translations/#alerts

**Expected behavior**
Warning should be removed

**Comment by Tobi823** [comment]
Thanks
