### ISSUE TITLE
Inclusion of FairEmail

### ISSUE THREAD

**Issue by sankhababu** [Tobi823/ffupdater#504]
Hi dev

Thanks for such essential app.

Though it is focused only for privacy-friendly browsers, could you extend this to include private email client app like FairEmail?

Regards

**Comment by Tobi823** [comment]
I'll have to think about that. 

- Adding support for FairMail would be out of scope for FFUpdater. 
- But email is (for me) as important as browser
- FairMail does not offer an F-Droid repo for faster updates
- Creating a new app only for updating mail apps (just for not breaking the scope of FFUpdater) would be a lot of work

**Comment by Tobi823** [comment]
I guess I tend to say "yes" (to include FairMail) ... but I'm not sure. And if I include FairMail, I also have to include K-9 Mail. AFAIK these are the two relevant open source mail clients.

**Comment by Usland123** [comment]
Orbot is also out of scope

**Comment by chris122380** [comment]
If including Fairemail make sure to be using the GitHub build as it's the latest version (newer then F-droid and the Play Store).

**Comment by sankhababu** [comment]
> If including Fairemail make sure to be using the GitHub build as it's the latest version (newer then F-droid and the Play Store).

Right you are 👍
Actually for this reason, that is to stay updated precisely I appealed to the dev to include it 😊

**Comment by chris122380** [comment]
> I guess I tend to say "yes" (to include FairMail) ... but I'm not sure. And if I include FairMail, I also have to include K-9 Mail. AFAIK these are the two relevant open source mail clients.

I am ok with adding K-9 mail (or Thunderbird whenever they decide to change its name). Just like there are other subcategories when adding an app there could be an email subcategory. Email and browsers tend to be the most popular on non-Google devices.

**Comment by Tobi823** [comment]
Done
