### ISSUE TITLE
Suggestion: Add Brave Beta and Nightly versions

### ISSUE THREAD

**Issue by Napster8** [Tobi823/ffupdater#51]
Since the Brave is chosen to be added, it makes sense to add these variants to the app as well.

Nightly: https://play.google.com/store/apps/details?id=com.brave.browser_nightly&hl=en_IN&gl=US

Beta: https://play.google.com/store/apps/details?id=com.brave.browser_beta&hl=en_IN&gl=US

**Comment by TPS** [comment]
Perhaps https://github.com/brave/brave-browser/releases would be useful instead of links above, but probably already aware, if pulling [releases](https://github.com/brave/brave-browser/releases/tag/v1.26.74) from there currently?

**Comment by Tobi823** [comment]
It's implemented and will be part of the next release
