### ISSUE TITLE
Tor Browser fails to find URL to check for update

### ISSUE THREAD

**Issue by Devilbroz** [Tobi823/ffupdater#511]
**Describe the bug**
The application fails to find a specific URL when attempting to look for an update for the TOR Browser

**To Reproduce**
1. Open Application

**Expected behavior**
I would expect to either see the application is updated or that there is an update available to install

**Error message from FFUpdater**
Stacktrace:
```
java.lang.IllegalStateException: Can't find download url with regex pattern '(https://dist\.torproject\.org/torbrowser/(.+)/.+-android-aarch64-multi\.apk)'.
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser.extractVersionAndDownloadUrl(SourceFile:14)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser.access$extractVersionAndDownloadUrl(Unknown Source:0)
	at de.marmaro.krt.ffupdater.app.impl.TorBrowser$extractVersionAndDownloadUrl$1.invokeSuspend(Unknown Source:12)
	at w3.a.resumeWith(Unknown Source:8)
	at j4.i0.run(Unknown Source:94)
	at m4.e.run(Unknown Source:11)
	at n4.j.run(Unknown Source:2)
	at n4.a$a.run(SourceFile:9)
```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.2.0 (113) release |
| Device | Z6530V (VSBL_Z6530V, Z6530, spacexm) |
| Manufacturer | ZTE (ZTE) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 9 (SDK: 28) |
| OS | scl_xa242_074, unknown, release-keys, 1602225535000 |

**Comment by Tobi823** [comment]
I found the issue and fixed it in version 78.2.5. It seems that you are using the FFUpdater version signed by F-Droid - but it will take some time until the fix is released on F-Droid.

You can either temporary uninstall the Tor Browser or install the latest version from Github/Gitlab (https://github.com/Tobi823/ffupdater/releases/tag/78.2.5, https://gitlab.com/Tobiwan/ffupdater_gitlab/-/releases/78.2.5)

**Comment by Tobi823** [comment]
Or maybe you are using the FFUpdater version signed by me (aka Github version). Then you can:
- download the APK file from Github/Gitlab () and install it
   - https://github.com/Tobi823/ffupdater/releases/tag/78.2.5
   - https://gitlab.com/Tobiwan/ffupdater_gitlab/-/releases/78.2.5
- use F-Droid with my own repository to update FFUpdater
- temporary uninstall Tor Browser + update FFUpdater in FFUpdater

**Comment by Devilbroz** [comment]
Amazingly fast work! Thank you so much!!

**Comment by Devilbroz** [comment]
How do I find your repository on F-Droid?

**Comment by Tobi823** [comment]
https://github.com/Tobi823/ffupdater/blob/master/docs/other_distribution_channels.md#f-droid-repository

**Comment by Tobi823** [comment]
I will create a short video to make it easier for all users

**Comment by Devilbroz** [comment]
I added your repo to F-Droid, but I don't see version 78.2.5 available

**Comment by Devilbroz** [comment]
Got it!! Thanks so much!

**Comment by Tobi823** [comment]
Thanks and no problem :)

Uploading and showing a video on Github is more difficult than I thought. Anyway - the video is finally online https://github.com/Tobi823/ffupdater/blob/master/docs/other_distribution_channels.md#method-1
