### ISSUE TITLE
Fennec F-droid didn't update

### ISSUE THREAD

**Issue by chris122380** [Tobi823/ffupdater#519]
**Describe the bug**
Fennec F-droid receiver a update from F-droid but FFupdater didn't see the update. If using the same repository unsure why FFupdater didn't see the update. 

**To Reproduce**
1. Check for update with F-droid 
2. Check for update with FFupdater 

**Expected behavior**
F-droid is showing Fennec 118.2.0
FFupdater is showing latest update of Fennec 118.1.0

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:
Didn't get an error unsure where to get the logs from.

**Comment by chris122380** [comment]
It has finally seen the update but about 2-3 days late. Unsure why the delay if using the same repo to pull from.

**Comment by Tobi823** [comment]
Did you enforce an update check in FFUpdater by swiping down? Maybe the background update check was delayed by batterie optimizations (a problem on Huawai, Samsung and some more devices)

**Comment by chris122380** [comment]
> Did you enforce an update check in FFUpdater by swiping down? Maybe the background update check was delayed by batterie optimizations (a problem on Huawai, Samsung and some more devices)

Yes I did. I did it a few times on cell service and Wi-Fi with the same results. I tried two different networks thinking it could have been the network but made no difference. I'm always playing around with different browsers so I just went ahead and grabbed it from F-droid.

**Comment by chris122380** [comment]
I just go to notification from F-droid that Fennec 119 is available but FFupdater doesn't show it if I refresh it. I haven't installed it yet in case there is something I need to collect for you. 

I have manually refreshed FFupdater and it's not seeing the update. Could it be different mirrors being used?

**Comment by Tobi823** [comment]
> Could it be different mirrors being used?

I don't any mirrors. FFUpdater only checks  https://f-droid.org/api/v1/packages/org.mozilla.fennec_fdroid for updates and "guesses" the download url (the download url ist always: https://f-droid.org/repo/${packageName}_${versionCode}.apk=

**Comment by Tobi823** [comment]
Either F-Droid has temporary remove the latest version of Fennec 119 or FFUpdater still uses some cached network responses.

**Comment by Tobi823** [comment]
I will close it for now because I don't know how to analyse it further.
