### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by devilhardcore** [Tobi823/ffupdater#523]
**Before you create a new issue please verify:**

- [x] I am using the latest version of FFUpdater.
  - Latest version for F-Droid users: https://f-droid.org/packages/de.marmaro.krt.ffupdater/
  - For all other users: https://github.com/Tobi823/ffupdater/releases/latest
- [ ] There are no other similar issues.
  - Please check the latest 5 bug issues (https://github.com/Tobi823/ffupdater/issues?q=is%3Aissue+label%3Abug+sort%3Aupdated). 
  - If you have any doubts, you can create a new problem. 
  - However, if there is a similar problem, please add your information to the existing issue.
- [x] You can tick boxes with an `x`

**Describe the bug**

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:

**Comment by Tobi823** [comment]
I can't see your bug report. I am very confused about your issue.
