### ISSUE TITLE
FairEmail is still supporting OAuth for Gmail

### ISSUE THREAD

**Issue by kazushi3** [Tobi823/ffupdater#539]
In FFUpdater, when I open infomation of FairEmail, it says "This version does not support OAuth and therefore does not support Gmail.". But FairEmail on F-Droid says "Note that OAuth was not approved by Google, etc for the F-Droid build. For this you'll need to use the Play store version or the GitHub release.". I think FFUpdater uses GitHub build so this warning should be removed.

**Comment by Tobi823** [comment]
Here is the link to the ticket https://github.com/Tobi823/ffupdater/issues/533

**Comment by Tobi823** [comment]
> OAuth access is available only for Play Store and Github releases because email providers permitted the use of OAuth for these releases only. The responsible for a release, for the F-Droid build this is the F-Droid organization, needs to ask for OAuth permissions, which mostly involves signing a contract with binding terms and conditions.

https://github.com/M66B/FairEmail/blob/master/FAQ.md#faq147

According to the documentation you are right - OAuth should work. But maybe something has changed and the documentation was not updated yet.

**Comment by kazushi3** [comment]
FairEmail's [readme.md](https://github.com/M66B/FairEmail) also says GitHub version supports OAuth. I'm using FairEmail updated by FFUpdater but still connected to Gmail via OAuth.

I've checked #533. I think users and author did not understand FFUpdater. Google Play version's paied features (called Pro) may be broken by FFUpdater but OAuth is Okay.

(I wrote Japanese translation of FairEmail and FFUpdater. Not as author but I know both of apps.)

**Comment by kazushi3** [comment]
Warning should be changed like this:
- This is GitHub version. Updating from other version may cause trouble. Do NOT ask FairEmail author to support about FFUpdater.

**Comment by Tobi823** [comment]
This will be part of the next release.

**Comment by licaon-kter** [comment]
App passwords work with Gmail in Fairemail from F-Droid, just that Google acts like an a$$hole.

Not easy, not hard: https://forum.f-droid.org/t/news-access-removal-of-less-secure-apps-in-google/17797/68
