### ISSUE TITLE
How to dismiss monitored apps

### ISSUE THREAD

**Issue by hank-tu-biz** [Tobi823/ffupdater#540]
For some reason ffup- adds FairEmail to its list of monitored apps. Further, I can find no way to delist it. (I never added it in the first place.) Can you add a function to delist apps that I want delisted?

**Comment by hank-tu-biz** [comment]
I want to delist apps to clean up the clutter. For some apps I definitely want to use your (enormously helpful) app. But also, as a complete noob, I have learned  to pay attention to exactly which repository I install and update from. [I hate signature conflics. I sometimes do and sometimes do not want to be on the bleeding edge of software updates. I'm 73, and I do screw up. And /mea culpa/, I'm a control freak.]

I'm in the USA in the country up north of Seattle. English is my first language. How about you? I want to say again how much I appreciate your contribution. It benefits us all, worldwide. Muchas gracias.

Regards,

•Hank

Nov 29, 2023 07:42:11 Tobias Hellmann ***@***.***>:

**Comment by hank-tu-biz** [comment]
Color me amazed. Thank you very much. There aren't many apps that make me positively orgasmic, but this is one. Mr. Hellmann, my very best regards!

Dec 2, 2023 14:14:10 Tobias Hellmann ***@***.***>:

**Comment by ihatemakinganaccount** [comment]
Sweet 😄
