### ISSUE TITLE
Wrong link: K-9 Mail

### ISSUE THREAD

**Issue by MailYouLater** [Tobi823/ffupdater#543]
**Important first questions**

1. Is your FFUpdater up-to-date? If not, please abort and update FFUpdater.
   - [x] Affected versions: 78.4.0, 79.0.0, 79.0.1

2. Do you spot similar issues in https://github.com/Tobi823/ffupdater/issues?
   - [x] Searched: No related issues already exist.

**Describe the bug**
The link associated with K-9 Mail in FFUpdater is to the source code of the website (K-9Mail.app) not the source code of the app (like all the other apps listed on FFUpdater).

**To Reproduce**
Please insert the steps to reproduce the behavior here:
1. Tap the info button on the K-9 Mail.
2. Tap the URL shown in the info dialog window.
   - https://github.com/k9mail/k9mail.app
3. Notice that the readme says "This GitHub repository provides the source for [K-9 Mail's website](https://k9mail.app/)."

**Expected behavior**
The linked URL should be https://github.com/thunderbird/thunderbird-android, which provides the source for the K-9 Mail app, instead of its website.

**Error message from FFUpdater**
N/A

**Comment by Tobi823** [comment]
Thanks for the info

**Comment by MailYouLater** [comment]
@Tobi823: Thanks.  I'm not that familiar with your codebase, but it looks like 9ce208f1c0b45de28e9da5c1df6da486667855b0 should fix this reference in the app itself.  However, I'm wondering... I realise these locations aren't 'functional' in the same way that that instance was, but should https://github.com/Tobi823/ffupdater/blob/9ce208f1c0b45de28e9da5c1df6da486667855b0/ffupdater/src/main/java/de/marmaro/krt/ffupdater/app/impl/K9Mail.kt#L16 and https://github.com/Tobi823/ffupdater/blob/9ce208f1c0b45de28e9da5c1df6da486667855b0/README.md?plain=1#L44 be changed over to this URL as well?
