### ISSUE TITLE
Add Cromite to the list of supported browsers

### ISSUE THREAD

**Issue by dr460nf1r3** [Tobi823/ffupdater#544]
[Cromite](https://github.com/uazo/cromite) is a fork of Bromite, providing most of its features after the original project has been discontinued. Having it added to the list of supported browsers would be great.

**Comment by Tobi823** [comment]
Cromite is already supported by FFUpdater. 

But you are not the first one how ask for a feature which already supported - how did you miss it and how can I make the project README more clearer?

**Comment by Tobi823** [comment]
Ich frag nur aus Neugier, mehr nicht :)

**Comment by dr460nf1r3** [comment]
In this case I have to take full responsibility for being blind, no idea how I missed this 😅 I'm sorry for taking up your time.
