### ISSUE TITLE
Updated GitHub repo for K-9

### ISSUE THREAD

**Issue by clayb91** [Tobi823/ffupdater#547]
**Important first questions**

1. Is your FFUpdater up-to-date? Yes

2. Do you spot similar issues in https://github.com/Tobi823/ffupdater/issues? No

**Describe the bug**
Thunderbird moved the repo for K-9 Mail to https://github.com/thunderbird/thunderbird-android/releases, so FFUpdater no longer downloads the latest version. Blog post with details on renaming: https://blog.thunderbird.net/2023/11/thunderbird-for-android-k-9-mail-october-2023-progress-report/

**To Reproduce**
Please insert the steps to reproduce the behavior here:
1. Open FFUpdater
2. Tap add application 
3. Tap K-9 Mail

**Expected behavior**
Download K-9 latest from current repo

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here: No error

**Comment by MailYouLater** [comment]
Actually... I believe that _is_ where FFUpdater downloads K-9 Mail from.
As can be seen in this screenshot:
![Download Application
Fetched metadata from GitHub
Downloading application (69%)
https://github.com/thunderbird/thunderbird-android/releases/download/6.603/k9-6.603.apk](https://github.com/Tobi823/ffupdater/assets/1279475/354e3a3c-1174-467a-b215-e33c172d04e2)

Note however that FFUpdater is set to download the latest _Stable_ release of K-9 Mail, so it won't update you to versions that are marked "Pre-Release".

Someone please correct me if I'm wrong, but I don't believe FFUpdater currently supports offering updates to Pre-Release versions of apps which use the same Package ID as the Stable releases.  I certainly haven't noticed any related options in recent versions of FFUpdater.

If you think FFUpdater should offer support for updating to Pre-Release versions of apps like K-9 Mail (where both releases use the same Package ID), I recommend you to open a feature request to ask for it.

**Comment by clayb91** [comment]
Yep, that's a good call. I didn't notice the pre release tag on the latest in the repo. Definitely should be the latest stable.
