### ISSUE TITLE
Installation/Update Bug

### ISSUE THREAD

**Issue by arghya339** [Tobi823/ffupdater#549]
**Important first questions**

1. Is your FFUpdater up-to-date? If not, please abort and update FFUpdater.
FFUpdater_79.1.0

2. Do you spot similar issues in https://github.com/Tobi823/ffupdater/issues? If yes, please abort and add your error message as a comment to the existing issue.
No

**Describe the bug**
Replace this paragraph with a clear and concise description of what the bug is.
¹When install any app on FFUpdater using ROOT installation method, Automatic Background Update unavailable. But it's also fine when you install though session installation method.
²FFUpdater not asking superuser request, when you turn off superusers on Magisk then open FFUpdater then settings then installation method then select session then root, then go back to FFUpdater home then click add then select & installation any app, you see session-installation('Update' button) tost message.

**To Reproduce**
Please insert the steps to reproduce the behavior here:
1. ...
2. ...
3. ...
me not a developer, sorry sir

**Expected behavior**
Please give a clear and concise description of what you expected to happen.
App Update using FFUpdater

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:

Sorry for G.Photos link, GitHub warn me 'This video is too big.'
Video:
https://photos.app.goo.gl/Sx4hH9v1fHoq1ukw9

**Comment by Tobi823** [comment]
1) Seems to be similar to #552. If the app was installed with root or Shizuku, the "was app installed by FFUpdater" detection breaks.

I have to think what is the best solution:

- If using root or Shizuku, update all apps. But this could breaks FairEmail
- FFUpdater can store if an app was installed or updated by FFUpdater (or: don't use the Android API to check, if an app was installed by FFUpdater)
- Use some other Android API
- ....

**Comment by Tobi823** [comment]
2. I'm not use if I understand you correctly. 

The bug: FFUpdater dont check if it still has root permission.
Solution: Check for root permission every time the main view is started.

Correct?
