### ISSUE TITLE
Where is Tor nightly?

### ISSUE THREAD

**Issue by rabaimor** [Tobi823/ffupdater#564]
It would be really convenient since checking and updating it manually is kind of a hassle. Also Tor stable and alpha are already in, so I'm kinda surprised why nightly isn't already.

**Comment by Tobi823** [comment]
I was not aware that a nightly variant of the Tor browser even exists.

**Comment by Tobi823** [comment]
On https://dist.torproject.org/torbrowser/ only stable and alpha are distributed.

**Comment by Tobi823** [comment]
And I think I should focus more on fixing the existing bugs. And honestly I don't think that so many users would use a nightly version (when stable and alpha exists).

**Comment by rabaimor** [comment]
> And I think I should focus more on fixing the existing bugs. And honestly I don't think that so many users would use a nightly version (when stable and alpha exists).

Adding this wouldn't hurt anyone though:
https://nightlies.tbb.torproject.org/nightly-builds/tor-browser-builds/

But I already found a solution to keep this and all my other apps up to date
