### ISSUE TITLE
Multiple updates from notification with already downloaded files installed first one every time.

### ISSUE THREAD

**Issue by sanctimoniousape** [Tobi823/ffupdater#565]
I try to have FFU install updates automatically via Shizuku, but my phone frequently kills it despite the battery use being unrestricted & the phone having plenty of RAM.  Whenever there are updates of multiple browsers, FFU dutifuly keeps the APKs as instructed & gives me notifications.

The problem is when I launch an update via one of the notifications, the first one I told it to install gets reinstalled on each subsequent browser. For example, when I start with the notification for Firefox, and then tap the notification for any other browser FFU reinstalls Firefox again. I have to launch the updates from within the app to get them to work. I suspect this is due to the fact once FFU is running from the first update, Android launches it with the same parameters if it's still an active task/process instead of using new ones associated with the different notification (I haven't programmed in nearly two decades, so this is just my best guess).

Ideally, I'd like to have the notification encompass all the browsers and taping it makes the app (optionally) automatically process all available updates.  That, or have an "update all" button in the main app interface and/or notification.

Thanks for your attention to this issue, as well as for this very useful app.

**Comment by Tobi823** [comment]
Done 
[Screen_recording_20240409_000049.webm](https://github.com/Tobi823/ffupdater/assets/10066140/6ef4bbe5-83e3-4a94-95b7-ad86135f21b7)

It will be part of the next update
