### ISSUE TITLE
Add lynket browser

### ISSUE THREAD

**Issue by UnforgivableStone** [Tobi823/ffupdater#567]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add lynket browser to ffupdater

**Additional context**
Its open source, and uses googles custom tab protocol.

**Comment by chris122380** [comment]
This browser hasn't been updated in over 4 years. Why would they want to add a browser that's no longer under development?

**Comment by Tobi823** [comment]
I understand that even maintaining a Chromium fork is a lot of work. But adding a browser that is very rarely updated is a disservice to most FFUpdater users.
