### ISSUE TITLE
"Delete APK after successful update" does not work anymore

### ISSUE THREAD

**Issue by HarriBuh** [Tobi823/ffupdater#569]
**Is your feature request related to a problem? Please describe.**
The app uses a surprisingly high amount of space on the phone (only 13,37 MB of the app itself, but 656 MB of user data!!), although I only have one repo subbed (Brave browser) and I have auto-deletion of the downloaded apk files activated.

**Describe the solution you'd like**
At least half the size of the app, only use minimum space required (= only absolutely necessary/ selected data).

**Comment by Tobi823** [comment]
> 13,37 MB of the app itself

In the past I tried to minimize the size of the APK file. But in the end I had to disable some optimization to keep the real method/class names and the line numbers.

>  656 MB of user data

I guess that this is more important than reducing the 13MB of app itself :) I suspect that some downloads were not deleted. Can you check which files are in your Android/data/de.marmaro.krt.ffupdater/Download directory?

**Comment by Tobi823** [comment]
I checked Android/data/de.marmaro.krt.ffupdater/Download and it seems that the latest APK of each app is still being stored.

**Comment by Tobi823** [comment]
I suspect that the "delete APK if installation was successful" is broken. My app is currently using 0.99GB of user data 😆

**Comment by Tobi823** [comment]
![Screenshot_20240218-163408](https://github.com/Tobi823/ffupdater/assets/10066140/6c323117-588b-4016-ab7a-d6b1a820a082)

**Comment by Tobi823** [comment]
![Screenshot_20240218-163205](https://github.com/Tobi823/ffupdater/assets/10066140/4ed4590e-0f3c-4222-aafa-3fe776011fcf)

**Comment by Tobi823** [comment]
will be fixed in the next FFUpdater version
