### ISSUE TITLE
Self-Updated to 79.1.1, Now All Apps are Marked Not Installed by FFU

### ISSUE THREAD

**Issue by sanctimoniousape** [Tobi823/ffupdater#571]
Updated itself I presume due to most recent release not yet available on F-droid.  Now every browser I've got FFU managing is marked as not installed by FFU (off-brownish color background in browser list) - including ones not available on the Play Store, so that's not the issue.  Should I be concerned?  Not sure if that's a sign of a security issue.

Android 11, using Shizuku, OnePlus 7 Pro.

**Comment by Tobi823** [comment]
Can you add a screenshot? That would help :)

**Comment by Tobi823** [comment]
> most recent release not yet available on F-droid.

It takes some time until the build and release the APK. My merge request were already accepted https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14556

**Comment by sanctimoniousape** [comment]
Sure, what do you want a screenshot of?  I'm not sure what I may not have been clear about?  I'll attach a shot of my installed browser list (more than most, I imagine, but I'll not bore you with an explanation).
![Screenshot_20240221-144930](https://github.com/Tobi823/ffupdater/assets/80165446/cc2fe21c-ee1e-4d0c-a63f-a183de16dcd4)

**Comment by Tobi823** [comment]
>  I've got FFU managing is marked as not installed by FFU 

I'm a bit in a hurry.  There can be multiple reasons why FFUpdater thinks that FFUpdater was not installed by FFUpdater :)

You can open FFUpdater and install the latest version FFUpdater again. That *should* fix the issue

> Should I be concerned?

No. The only downside side that automatic update for the app is disabled.

**Comment by Tobi823** [comment]
> Sure, what do you want a screenshot of? I'm not sure what I may not have been clear about? I'll attach a shot of my installed browser list (more than most, I imagine, but I'll not bore you with an explanation). ![Screenshot_20240221-144930](https://private-user-images.githubusercontent.com/80165446/306755935-cc2fe21c-ee1e-4d0c-a63f-a183de16dcd4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDUzNzMsIm5iZiI6MTcwODU0NTA3MywicGF0aCI6Ii84MDE2NTQ0Ni8zMDY3NTU5MzUtY2MyZmUyMWMtZWUxZS00ZDBjLWE2M2YtYTE4M2RlMTZkY2Q0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE5NTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYzk0Njc1NDA2Y2MwZDZjYWYyODYzMDQ1ZGQ5YWU0NGFjNTYwNTU3MDA5OTUzNGFlMmNlYjQ2MjZmMWQ4OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L0mg8dUdNhqciMk32nbXYBBDuanWcPaZtjPFa3qPUC8)

That is exactly what I wanted.

**Comment by sanctimoniousape** [comment]
> > most recent release not yet available on F-droid.
> 
> It takes some time until the build and release the APK. My merge request were already accepted https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14556

Yeah, I know. I mentioned it only to back up my deduction that the update to 79.1.1 didn't come from there.

**Comment by Tobi823** [comment]
I suspect that my "was app installed by FFUpdater" check does not work (anymore?) on OnePlus or with Shizuku. I have to look into it

**Comment by Tobi823** [comment]
Can you:
- switch the installer method from Shizuku to the default "package installer"
- update some of your apps
- and check if FFUpdater detects that these apps were installed by FFUpdater

If yes, then I have to look into Shizuku :)

**Comment by sanctimoniousape** [comment]
> I suspect that my "was app installed by FFUpdater" check does not work (anymore?) on OnePlus or with Shizuku. I have to look into it

Interesting. In the meantime, I'll try to have FFU update itself again as you suggested. Will let you know.  Thanks for the quick replies!

**Comment by sanctimoniousape** [comment]
> Can you:
> 
> * switch the installer method from Shizuku to the default "package installer"
> * update some of your apps
> * and check if FFUpdater detects that these apps were installed by FFUpdater
> 
> If yes, then I have to look into Shizuku :)

Yes, I had the same issue on another device of mine (Unihertz Jelly Star on A13). I went through the list manually updating them all, and it worked as expected.  Made me think a security certificate was changed, or something, which I then realized might be concerning  so I asked.

**Comment by sanctimoniousape** [comment]
Having FFU reinstall itself manually via session installer made it recognize the source of install (turned to normal background color).  If you're unconcerned about this being a security issue, then I'll do the rest from here.  Thanks, again!

**Comment by sanctimoniousape** [comment]
Both FFU & Fennec are now recognized.  I will wait on the rest until you give the all-clear security-wise.  No rush if you're still in a hurry.  I appreciate your tending to this so quickly as it is.

**Comment by sanctimoniousape** [comment]
Since you've not gotten back, and I don't see any other red flags raised since, I'm going ahead with updating my other apps.

Since this happened on my Unihertz phone as well, it seems assuming this is related to OnePlus oddities might not be the issue at hand. However, since I seem to be the only one reporting it, I may go ahead and close the issue shortly unless something comes up to make that an inappropriate action.

**Comment by Tobi823** [comment]
Sorry, I overlooked your e-mail.

There is no security problem because:
- Android does not allow app updates with different APK signatures. If the app still contains your bookmarks, settings etc. you are safe.
- Moreover, FFUpdater will throw an error with the APK signature is not correct. This did not happen in your case.

**Comment by Tobi823** [comment]
But keep the issue open. Maybe I discover the reason for this strange behavior :)

**Comment by sanctimoniousape** [comment]
Thanks for explaining why I shouldn't be concerned - I'm obviously aware of some of the security measures in use nowadays, but don't really know enough about them to speak intelligently on them.  I'll leave this question open as requested, and leave it to you to decide when it has been satisfactorily resolved.

Thanks once again for the quick responses, the extremely useful program, and the patience required to deal with someone who doesn't quite know what they're talking about (although I'll pat myself on the back somewhat for recognizing and admitting that fact).  Feel free to let me know if there's anything you'd like me to do to help you test anything.  Otherwise, take care.

**Comment by Tobi823** [comment]
I found the problem. In the native installer I forgot to register FFUpdater as the installation initiator. 🙈
