### ISSUE TITLE
Chromium: "Available" version number is not consistent with "Installed"

### ISSUE THREAD

**Issue by Elkiwa** [Tobi823/ffupdater#574]
**Describe the bug**

"Available" version number is not consistent with "Installed"

**To Reproduce**
Installed and updated chromium to the latest version:  ex. `124.0.6360.0`
However, the available version indicates `1273323`

**Expected behavior**
"Available" version number should be in consistent with "Installed" version number

**Error message from FFUpdater**

**Comment by Tobi823** [comment]
The download website of Chromium does not publish the version number. I can only fetch the latest revision number (1273323) and nothing more (see https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Android_Arm64%2FLAST_CHANGE?alt=media and )
