### ISSUE TITLE
Firefox Android CI links has been changed starting from version 126

### ISSUE THREAD

**Issue by monstorix** [Tobi823/ffupdater#579]
**Is your feature request related to a problem? Please describe.**
Mozilla has [announced](https://github.com/mozilla-mobile/firefox-android/wiki#upcoming-migration-to-mozilla-central) that as of March 18 2024, the Firefox Android repos will be moved to mozilla-central, meaning that the desktop and mobile versions now share the same CI directory starting with version 126.

FFUpdater currently still uses the old CI link for fenix-nightly, which stopped updating on 18 March.

**Describe the solution you'd like**
Use the new CI download link for Firefox Android Nightly:
https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/fenix-nightly

Other versions (Release/Beta/Focus) will also need to be migrated to new links in the future, when the version exceeds 126.

**Comment by Tobi823** [comment]
Thanks for the info, I will fix that.

**Comment by Tobi823** [comment]
If you can't wait until I release the improved version: 

[ffupdater-release.zip](https://github.com/Tobi823/ffupdater/files/14893542/ffupdater-release.zip)

(signed with my key like the releases on GitHub and GitLab)

**Comment by Tobi823** [comment]
I download Firefox Beta from https://github.com/mozilla-mobile/firefox-android/releases. Starting with Firefox 126 they want to move the source code to another repository. I guess I have to download Firefox Release/Beta and Focus/Klar from their CI pipeline.

**Comment by Tobi823** [comment]
#584 584
