### ISSUE TITLE
Please add a method to bypass the Google Play store update.

### ISSUE THREAD

**Issue by segln** [Tobi823/ffupdater#583]
First of all, I would like to thank you for a wonderful project.

**Is your feature request related to a problem? Please describe.**
I'm using FFUpdater well, but the Google Play store keeps trying to update Firefox.
I disabled automatic update for Firefox, but it's a hassle to use the Play Store's 'Update all' feature because Firefox is constantly added to the update list.

**Describe the solution you'd like**
There are some solutions to this like re-signing apks automatically when downloaded.
I would appreciate it if you could provide one of these methods.

Thank you for your consideration.

**Comment by Tobi823** [comment]
> I disabled automatic update for Firefox

Did you disabled that in FFUpdater or in Play Store?

Maybe I misunderstand you ... I would disable the automatic update of Firefox in FFUpdater and let Google Play Store automatically update Firefox.

**Comment by Tobi823** [comment]
Maybe Google Play Store tries to update Firefox because you installed Firefox with Google Play Store?

**Comment by Tobi823** [comment]
> There are some solutions to this like re-signing apks automatically when downloaded.

Can you name them? 😆  I have no experience/knowledge in it.

I only see that Android API offers a setRequestUpdateOwnership - but I can only call it when an app is installed (and not update) + only on Android 14.

**Comment by segln** [comment]
> Did you disabled that in FFUpdater or in Play Store?

No, I disabled Google Play's automatic update for Firefox. I do not want to update it from Google Play.

> Maybe Google Play Store tries to update Firefox because you installed Firefox with Google Play Store?

I installed Firefox from FFUpdater.
App info reports Firefox was downloaded from FFUpdater but Google Play tries to update it.

> Can you name them? 😆 I have no experience/knowledge in it.

What I previously mentioned was based on information similar to [this link](https://www.xda-developers.com/stop-updates-android-application).
But upon further search, I found out that starting from this year, Google Play attempts to update all apps regardless of certificates.
So... It won't be easy I think.

**Comment by ihatemakinganaccount** [comment]
@segln  People can't affect when Google is pushy...

Install some variant of FF that's not on Play Store (Fennec, Mull, IceRaven, idk which is or isn't) and/or don't use Play Store but Aurora Store to install updates for other apps. There you can set a blacklist to prevent updates for specific apps.

**Comment by segln** [comment]
@ihatemakinganaccount I'm using some apps that are only available on Google Play like bank apps... So I have to use Google Play partially. But thanks, that can be an option.

**Comment by ihatemakinganaccount** [comment]
@segln you can use Aurora Store to install those apps, it spoofs Play Store well enough that even banking apps shouldn't complain. Unless you need to use in-app purchases, you  don't need Play. And even then you can install the app using Play Store, disable the Play Store app and then use Aurora for updates.

**Comment by segln** [comment]
@ihatemakinganaccount Wow, you are right. I was able to access the banking app using the Aurora store. And maybe I can use alternative purchasing method wihout Google Play.

Thank you very much for your kind advice.

**Comment by segln** [comment]
I think this is Google's another fault again and will close the issue.
