### ISSUE TITLE
Use Mozilla CI instead of Github 

### ISSUE THREAD

**Issue by Tobi823** [Tobi823/ffupdater#584]
https://github.com/mozilla-mobile/firefox-android/issues/5900

**Comment by Tobi823** [comment]
https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v3.firefox-android.apks

**Comment by Tobi823** [comment]
https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v3.firefox-android.apks.fenix-release.latest/arm64-v8a

https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v3.firefox-android.apks.fenix-beta.latest/arm64-v8a

https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v3.firefox-android.apks.focus-release.latest/arm64-v8a

https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v3.firefox-android.apks.klar-release.latest

**Comment by Eric-01** [comment]
Perhaps archive.mozilla.org would be a better choice?

Some time ago, a user noticed that artifacts for Firefox Nightly for Android are no longer created by the (previous) Mozilla CI. This information was shared on the Firefox subreddit. Among those who participated in the conversation was @evilpie, one of the Mozilla employees, who wrote:

> Not surprising, because Firefox for Android moved from github to mozilla-central. I don't think we really want people to directly use CI instead of archive.mozilla.org.

Source: https://www.reddit.com/r/firefox/comments/1brf1uv/firefox_nightly_for_android_didnt_get_updated_for/

**Comment by Tobi823** [comment]
Thanks for the info. I totally forgot that archive.mozilla.org existed. I will try to find the links :)

org.mozilla.firefox_beta: https://archive.mozilla.org/pub/fenix/releases/126.0b4/android/fenix-126.0b4-android-arm64-v8a/

**Comment by Rob--W** [comment]
> I could try to parse the result from https://archive.mozilla.org/pub/fenix/releases/ and try to find the highest version value. But that can be tricky.

The version format and ordering is documented at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/version/format

An example of a version comparator implementation is at https://github.com/mozilla/addons-moz-compare

**Comment by Eric-01** [comment]
There is an endpoint at download.mozilla.org that serves the legacy Firefox for Android a.k.a. Fennec:
- https://download.mozilla.org/?product=fennec-latest&os=android&lang=multi
- https://download.mozilla.org/?product=fennec-beta-latest&os=android&lang=multi
- https://download.mozilla.org/?product=fennec-nightly-latest&os=android&lang=multi

However, I have no idea whether something similar has been created for the rewritten Firefox for Android or not. I'm afraid that no one might have bothered to prepare something like this.

**Comment by Eric-01** [comment]
Now that both desktop and mobile Firefox are hosted in the large Mozilla repo, this may be something worth taking into consideration. It would save Tobi823 and maintainers of other similar projects the trouble of parsing versions themselves. @Rob--W, would you be able to reach out to the mobile team or sysops at Mozilla and pass this on to them?

**Comment by Tobi823** [comment]
@Eric-01 I asked the developers on their Matrix chat (https://chat.mozilla.org/#/room/#fenix:mozilla.org):

1. I can use Mozilla CI or archive.mozilla.org - it does not matter.

2. Maven Central does not contain artifacts like APK files.

3. There is also ftp.mozilla.org, but I looks like archive.mozilla.org

**Comment by Tobi823** [comment]
I will fix this tomorrow (21.05). Weekend was a bit busy.

**Comment by Attigliuzzo** [comment]
There is an error while ffupdater tries to reach the new Mozilla site:

![photo1716359228](https://github.com/Tobi823/ffupdater/assets/42100711/7ad7370a-a4c4-4cde-b07b-457a350e323b)

**Comment by sanjayen** [comment]
@Tobi823 Firefox Nightly updates, for the same version, do not get prompted. FFUpdater checks the file timestamp and shows a newer update time. However, the download button does not change colour.

A version change correctly prompts the download by changing the download icon colour.

Was working in the earlier version but probably has to do with the repository change to Mozilla CI.

**Comment by Tobi823** [comment]
> @Tobi823 Firefox Nightly updates, for the same version, do not get prompted. FFUpdater checks the file timestamp and shows a newer update time. However, the download button does not change colour.
> 
> A version change correctly prompts the download by changing the download icon colour.
> 
> Was working in the earlier version but probably has to do with the repository change to Mozilla CI.

Thanks for the information. I will fix it this weekend.
