### ISSUE TITLE
Not finding the latest version of FF Beta

### ISSUE THREAD

**Issue by Word66** [Tobi823/ffupdater#590]
**Important first questions**

1. Is your FFUpdater up-to-date? If not, please abort and update FFUpdater.

Yes

2. Do you spot similar issues in https://github.com/Tobi823/ffupdater/issues? If yes, please abort and add your error message as a comment to the existing issue.

No

**Describe the bug**
On checking for the latest version of Firefox Beta (currently 127.0b6) it returns version 127.0b1

**To Reproduce**
Please insert the steps to reproduce the behavior here:
1. Open FFUpdater
2. Check for latest versions

**Expected behavior**
The latest version of Firefox Beta should be returned.

**Error message from FFUpdater**
No error.

![Screenshot_20240523-152249](https://github.com/Tobi823/ffupdater/assets/4042359/712059d0-26f9-43cd-8aca-29d57e3bc79d)

**Comment by Tobi823** [comment]
Will be fixed with the next version

**Comment by Word66** [comment]
Looks good in 79.2.3
