### ISSUE TITLE
Do not download updates when battery saver is enabled

### ISSUE THREAD

**Issue by kaikli** [Tobi823/ffupdater#607]
**Is your feature request related to a problem? Please describe.**
I have noticed that ffupdater dosen't respect the battery saver setting. Even if activated the app downloads updates automatically in the background.

**Describe the solution you'd like**
Add a option to disable automatic sync/download in the background when power saving mode is activated.

**Comment by Tobi823** [comment]
I would prefer a solution without adding a new setting option.

What do you think to this proposal?

If the battery saver is enabled for less than 24h, then don't check for updates.
If it is enabled for longer than 24h, then only check for updates and don't download the APK files in the background.

**Comment by kaikli** [comment]
This would be fine.
Maybe reduce the update interval when the battery saver is enabled? Especially for people who set this setting lower than 4 hours.

How do you plan to detect how long the battery saver is enabled? Is there a timestamp you can read from Android or would you save the status of the last update check? Or maybe set a timer for 24h when the battery saver is enabled and reset this timer when the battery saver is deactivated again.

**Comment by Tobi823** [comment]
I think that I can register a listener/callback when the "power save mode" is changed. https://developer.android.com/reference/android/os/PowerManager#ACTION_POWER_SAVE_MODE_CHANGED

And when it is changed, I can store the time. 

But I have to still test it :)

**Comment by Tobi823** [comment]
It is now implemented 65e6e79

I will implement the next days.
