### ISSUE TITLE
Firefox Nightly Update Check: Compare version string and datetime

### ISSUE THREAD

**Issue by ericJrdn** [Tobi823/ffupdater#618]
**Describe the bug**
FFUpdater 79.2.4 (and 79.2.2) is able to see that a new version of Firefox Nightly is available but does not show the download arrow.

**To Reproduce**
1. Add FireFox Nighly as a new application
2. Refresh the main screen. It displays that a new version is available. There is no arrow to download the available version

**Expected behavior**
There should be an arrow as in 79.2.0 to download Firefox.
79.2.0 and 79.2.4 should display the same available FireFox version. That's not the case.

**Error message from FFUpdater**
None
![Screenshot_20240708-193536](https://github.com/Tobi823/ffupdater/assets/64037055/40ca0bba-90cd-4af9-8719-5238542b4f81)
![Screenshot_20240708-193603](https://github.com/Tobi823/ffupdater/assets/64037055/6d882f3d-c34f-4bec-9234-a66d8e3716d2)

**Comment by Tobi823** [comment]
I see the problem. I'm only comparing the version string (e.g. "129.0a1") and not the version string + date + time.

FFUpdater downloads Firefox Nightly from https://archive.mozilla.org/pub/fenix/nightly/2024/07/ and the version string always stays at "129.0a1"

**Comment by ericJrdn** [comment]
Thank you
And thank you for this software

**Comment by Tobi823** [comment]
A bit late but I finally found a good way to check if a new Firefox Nightly version was released (even if the version number like 133.0.a1 stays the same).

FYI:

The build date is displayed on archive.mozilla.org and also written to multiple asset files inside the APK file.

My strategy is now to read the build date (from the asset file from the installed Firefox Nightly) and compare it against all available versions on https://archive.mozilla.org/.


b2eb7e2b

![image](https://github.com/user-attachments/assets/538d34b2-e3cc-4b35-b2ce-25a28b9f2132)

**Comment by Tobi823** [comment]
Fixed in version 79.2.5
