### ISSUE TITLE
unexpected error occurred - tor browser alpha

### ISSUE THREAD

**Issue by Uj947nXmRqV2nRaWshKtHzTvckUUpD** [Tobi823/ffupdater#631]
**Important first questions**

1. Is your FFUpdater up-to-date? If not, please abort and update FFUpdater.
yes

2. Do you spot similar issues in https://github.com/Tobi823/ffupdater/issues? If yes, please abort and add your error message as a comment to the existing issue.
no

**Describe the bug**
Replace this paragraph with a clear and concise description of what the bug is.
on updates check, gives error for tor browser alpha

**To Reproduce**
Please insert the steps to reproduce the behavior here:
1. check updates
2. gives error for tor browser alpha

**Expected behavior**
Please give a clear and concise description of what you expected to happen.
no error

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:
unexpected error occurred

**Comment by Tobi823** [comment]
I need more information to understand the problem. Can you give me a screenshot, error message etc?

**Comment by Tobi823** [comment]
Nevermind, I can reproduce the error

**Comment by Tobi823** [comment]
Problem is now fixed in code 36d11deb829302a154917c4aa6af6e1dae059b80 . I will release a new FFUpdater version in the next days.

**Comment by Tobi823** [comment]
Version 79.2.5 should fix this problem
