### ISSUE TITLE
Add Thunderbird Beta

### ISSUE THREAD

**Issue by snoweuph** [Tobi823/ffupdater#633]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Thunderbird Android Beta (I want the Thunderbird branding and use  the Beta)

**Additional context**
Currently Theres just the K9 Mail app, which in the Futurte will become Thunderbird.
I want to use the Beta, to have the new Branding and write Bug reports

**Comment by rafnov** [comment]
Thunderbird 8.0 stable been released just hours ago. Is it possible to add it to FFUpdater?

Btw. They are not going to fully drop K-9 ATM, but maintain 2 apps in parallel.

**Comment by Tobi823** [comment]
Done thanks to @TeeTeeHaa

**Comment by TeeTeeHaa** [comment]
@Tobi823  While I consider it beneficial to have a mobile Thunderbird Beta provided by FFUpdater... why is it happening thanks to me?! 🤔

**Comment by Tobi823** [comment]
oh sorry, I meant @kewisch
