### ISSUE TITLE
Fennec F-Droid stuck at 129.0.2

### ISSUE THREAD

**Issue by CaseOf** [Tobi823/ffupdater#639]
Hello,

Fennec F-Droid isn't receiving updates since months and is now marked as having security risks on F-Droid client (Firefox based browsers <131.0.2 are vulnerable to a 0-day breach).

Should you warn users of FFUpdater about this ?

**Comment by Tobi823** [comment]
I'm currently on vacation for the next 2 weeks. 

But after it I will add the warning if Fennec is still outdated.

**Comment by Tobi823** [comment]
As far as I know there is a compilation problem and the current maintainer is working on it

**Comment by TeeTeeHaa** [comment]
Mozilla's Security Advisory 2024-51: https://www.mozilla.org/en-US/security/advisories/mfsa2024-51/

**Comment by Tobi823** [comment]
good to know, I will remove Fennec after my vacation

**Comment by SkewedZeppelin** [comment]
am one of the maintainers, this was fixed: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16135

**Comment by Tobi823** [comment]
Thanks for the information and your work @SkewedZeppelin
