### ISSUE TITLE
Error when downloading Firefox Release

### ISSUE THREAD

**Issue by Tobi823** [Tobi823/ffupdater#64]
The "API" for checking for new Firefox Release has changed again :(

But this time, I've made the check more robust.

Fix will be available in version 74.3.4

**Comment by Colfenor** [comment]
Thanks for the responsiveness ! could you elaborate a little more to what exactly has changed in the API this time ?

**Comment by Tobi823** [comment]
I'm using the "FirefoxCI" (https://firefox-ci-tc.services.mozilla.com/, https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.release.latest) for update checking and downloading.
Pros: Every version is released on there. There is no way, that a developer forgets to add the APK files to a new release (like on the GitHub repository)
Cons: I have to parse the chain_of_trust.log file to extract the version name.

But in the last days, this chain_of_trust.log has changed multiple times between:

A:
> 2021-05-28T02:16:41    DEBUG -  {'as_slugid': <function populate_jsone_context.<locals>.<lambda> at 0x7f46862649d0>,
 'clientId': 'project/releng/shipit/production',
 'input': {'build_number': 1,
           'next_version': '89.1.2',
           'previous_graph_ids': ['MuvyFf6mQ32jk4seFj3MPg'],
           'release_enable_emefree': False,
           'release_enable_partner_attribution': False,
           'release_enable_partner_repack': False,
           'release_eta': None,
           'release_promotion_flavor': 'ship',
           'version': '89.1.1'},
 'now': '2021-05-28T02:01:07.367Z',
 'ownTaskId': 'O6KIm18GR-ya7_RqaghYdg',
 'taskGroupId': 'MuvyFf6mQ32jk4seFj3MPg',
 'taskId': None,
 'tasks_for': 'action'}

B: 
> 2021-07-07T17:24:41    DEBUG -  {'as_slugid': <function populate_jsone_context.<locals>.<lambda> at 0x7fd7855c9f70>,
 'event': {'action': 'published',
           'release': {'published_at': '2021-07-07T17:11:45Z',
                       'tag_name': 'v90.1.1',
                       'target_commitish': 'aeedb6b53781c6d29fda9034267a4ce8aeed6468'},
           'repository': {'clone_url': 'https://github.com/mozilla-mobile/fenix.git',
                          'full_name': 'mozilla-mobile/fenix',
                          'html_url': 'https://github.com/mozilla-mobile/fenix',
                          'name': 'fenix'},
           'sender': {'login': 'moz-releng-automation'}},
 'now': '2021-07-07T17:11:47.822Z',
 'ownTaskId': 'NqqwsJyFQka76yJKacw-Dg',
 'taskId': None,
 'tasks_for': 'github-release'}

In my first fixes, I simply changed the RegEx+CaptureGroup to extract this version number from `'version': '(.+)'` to `'tag_name': '(.+)'` + removing first 'v'.

But now I've made the RegEx+CaptureGroup more flexible: `'(version|tag_name)': 'v?(.+)'` - it will support both forms.

**Comment by Tobi823** [comment]
I decide to release a self compiled version of FFUpdater - you can use if to bridge the waiting time for the F-Droid release.
See https://github.com/Tobi823/ffupdater#temporary-builds

**Comment by Tobi823** [comment]
Fix is available on F-Droid
