### ISSUE TITLE
Wrong version of Firefox Focus displayed

### ISSUE THREAD

**Issue by IZ2QDH** [Tobi823/ffupdater#69]
After updating Firefox Focus usin unofficial version 74.3.4 i noticed that the app notifies me to update it again but it displays:
Installed version: 8.18.0-rc.1
Available: 8.08.0
See attached screenshot
The issue is seen also on version 74.3.2 (F-Droid version)
![photo_2021-08-04_09-24-24](https://user-images.githubusercontent.com/20722059/128139279-32a9916e-7001-48d5-923f-1b00377dc13d.jpg)

**Comment by Tobi823** [comment]
That's strange.

https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.focus.release/latest returns "8.18.0" as version name.
But the APK file has the version name "8.18.0-rc.1".

I would fix this by removing the "-rc.1" when extracting the version name of the installed app.

**Comment by Tobi823** [comment]
more precisely: I will remove everything after the dash + the dash itself. For "8.18.0-rc.1" it would be "8.18.0"

**Comment by Tobi823** [comment]
Fix will be available in version 74.3.5 - but I don't know how long F-Droid takes to publish this version.
