### ISSUE TITLE
Firefox Focus Version now matches Firefox version

### ISSUE THREAD

**Issue by IZ2QDH** [Tobi823/ffupdater#72]
Finally F-Droid released version 74.3.4
I noticed that Firefox Focus version now matches Firefox version
Is it ok?
Screenshot below
Note: i updated Firefox Focus to version indicated and works, although that version does not esist on APKMirror
![Screenshot_2021-08-06-08-55-21-603_de.marmaro.krt.ffupdater.jpg](https://user-images.githubusercontent.com/20722059/128469260-a991ea0c-c40d-452a-a3fb-2bb975d3ee17.jpg)

**Comment by Gontier-Julien** [comment]
It seems to not be an issue but an official upstream choice to do it that way.
I can't official confirm this, but the Google play store version report the same version.

**Comment by Tobi823** [comment]
> I noticed that Firefox Focus version now matches Firefox version
Is it ok?

It seems. The build log from 05.08.2021 reads: 
> 'tag_name': 'v91.1.0',

But the guys from Mozilla have made a mistake. The version of the 64bit Firefox Focus APK file is not right:

Firefox Focus on arm64/64bit has the version name "8.18.0-rc.1"
Firefox Focus on armeabi/32bit has the version name "91.1.0"
Firefox Klar on arm64/64bit has the version name "91.1.0"
Firefox Klar on armeabi/32bit has the version name "91.1.0"

I hope the next 64bit Firefox Focus build has the right version name.

**Comment by IZ2QDH** [comment]
Firefox Focus has been updated to version 91.1.2
Maybe it's not a mistake?

**Comment by Tobi823** [comment]
I think it's not a mistake + Firefox Focus/Klar can be updated without a problem.

I will close this ticket.
