### ISSUE TITLE
[Suggestion] maybe create a repo for ffupdater for f-droid

### ISSUE THREAD

**Issue by Gontier-Julien** [Tobi823/ffupdater#73]
I think it will be awesome to have a f-droid repo fro ffupdater, where you can push the update and be more up-to-date when you release a new version, so we don't have to wait for f-droid to build it which can take some times.

**Comment by DevJackSmith** [comment]
Do you mean something like this? https://f-droid.org/en/tutorials/create-repo/

**Comment by Tobi823** [comment]
Thanks for the link :+1: 

It looks easier than I thought it would be. I was afraid that I would have to rent a (virtual) server and secure it.

I would prefer to publish FFUpdater only "normally" via F-Droid. (If someone takes over my computer, they have to upload the malicious code to the git repository for everyone to see. So the attacker can't hide malicious code in the FFUpdater APK file).

But I also understand that the waiting times for a quickfix are too long.

Currently I am busy. But I can try to create a F-Droid repository for FFUp in October.

**Comment by Tobi823** [comment]
Its done - and it was a lot of work.
Here's a little tutorial if anyone else wants to do it for a different app:

- repomaker is hardly maintain and is need of a maintainer-> lot of bugs. look into https://gitlab.com/fdroid/repomaker/-/issues
- use the docker-compose version from https://gitlab.com/fdroid/repomaker/-/tree/master/docker#docker-compose-deployment, the Flatpak version doesn't work (see https://gitlab.com/fdroid/repomaker/-/issues/251)
- create a GitHub or GitLab repository for storage (but you can use other Git-Repositories, SSH-Server or Amazon S3 buckets)
- do not use a underscore (`_`) in the repository name or it will not work
- read the README.md manual https://gitlab.com/fdroid/repomaker/-/tree/master/docker#docker-compose-deployment
- execute the docker-compose script and start repomaker
- create a account on your local running webservice (Firefox/Chrome on http://localhost) + log into your new account
- create in the webservice/browser a new repomaker repository with name and description
- add a signed APK file to this repomaker repository by drag+drop or clicking on "choose file"
- go to share > add storage > Git (or something different) > Enter the SSH URL for your Git repository > Enable "Primary Storage" > Save
- repomaker will generate a SSH key which you have to copy + add to your GitHub account
- update screenshots, descriptions of the app in your repomaker repository
- share the link in share > share public link
- look into the debug messages (from docker-compose) to verify that repomaker is executing the background job and uploading the APK file + metadata to the Git repository

**Comment by Tobi823** [comment]
If you want to try the F-Droid repository, go to https://github.com/Tobi823/ffupdater#f-droid-repository for further details.

**Comment by Tobi823** [comment]
I hope I don't upset the GitHub gods by using a GitHub repository as an F-Droid repository :smile:

**Comment by DevJackSmith** [comment]
Hmm, I seem to be getting an error :(

![Screenshot_20210928-184317.png](https://user-images.githubusercontent.com/8228441/135184218-7d97892b-b88a-4d4c-a8d1-43dfc412a3f9.png)

**Comment by Gontier-Julien** [comment]
It work perfectly with Foxy Droid, it not maintained atm, but it work a lot better than f-droid 😂

**Comment by Tobi823** [comment]
@DevJackSmith I can't reproduce your problem.

But I notice this: When I want to add my repository to F-Droid, it appends a space to the end of the "Repository address". 
`https://raw.githubusercontent.com/Tobi823/ffupdaterrepo/master/fdroid/repo` becomes `https://raw.githubusercontent.com/Tobi823/ffupdaterrepo/master/fdroid/repo `.

The space at the end will be converted to `%0A`: `https://raw.githubusercontent.com/Tobi823/ffupdaterrepo/master/fdroid/repo%0A`.
And this repository address will not work and F-Droid marks this repository as "Unverified".

**Comment by Tobi823** [comment]
This is how it works on my smartphone.

F-Droid will read my clipboard. But I have to remove the last space from the "Repository address"
![step1](https://user-images.githubusercontent.com/10066140/135270124-9ee09f94-0043-497a-870a-7d85e0f2f619.png)
![step2](https://user-images.githubusercontent.com/10066140/135270181-4a5502e4-1206-4389-a3e2-8bbd6f43e884.png)
![step3](https://user-images.githubusercontent.com/10066140/135270200-563e0d91-3f46-4ddd-b0e0-ffa2e54c7348.png)

The repository is temporary "Unverified" until I reopen F-Droid.
![step4](https://user-images.githubusercontent.com/10066140/135270315-8f755249-9368-430d-a438-7da4df0402e1.png)
![step5](https://user-images.githubusercontent.com/10066140/135270324-8871285c-8aad-4d0c-9af0-413e1d53da76.png)

Metadata about the F-Droid repository:
![step6](https://user-images.githubusercontent.com/10066140/135270374-336e3d4c-fc1e-43e2-a37d-2955f31bfacb.png)

**Comment by Tobi823** [comment]
@DevJackSmith another guess - maybe the QR code is broken?

**Comment by DevJackSmith** [comment]
Tried it a few more times. Here's what I found out. When I select the url (with fingerprint in it) Android has a menu popup with the usual copy, cut, paste options and open with Fdroid option. That Open with Fdroid option opens Fdroid and pastes the url into repo url field and fingerprint into fingerprint field. That doesn't work, it gives error above. I tried doit the same thing manually by copy and pasting url into url field and fingerprint into fingerprint field. Same error.

However! If I just copy the whole url with fingerprint into url field, it first has a small warning note that the repo is unverified, but then after refresh everything just works and no warning. Good job!! Thanks for making this happen!!

**Comment by DevJackSmith** [comment]
@Tobi823 ^^

**Comment by DevJackSmith** [comment]
If it helps I'm on
pixel 3 xl
Android 11 build RQ3A.210905.001

Fdroid 1.13.1

**Comment by Tobi823** [comment]
@DevJackSmith I've improved the installation process of the FFUpdater repository.

Can you remove the repository from your F-Droid client and add it again according to https://github.com/Tobi823/ffupdater#f-droid-repository and https://gitlab.com/Tobiwan/ffupdater_gitlab#f-droid-repository? There are differences between GitHub and GitLab.

**Comment by Tobi823** [comment]
@Gontier-Julien can you try (the new installation manual) too? 

I simply copied the "Add to F-Droid" button from the index.html page of the repository. :smile:

**Comment by Gontier-Julien** [comment]
@Tobi823 work like a charm ^^

**Comment by DevJackSmith** [comment]
All of them work now. Sweet! Ty
