### ISSUE TITLE
Hash verification fails (Firefox and Firefox Preview)

### ISSUE THREAD

**Issue by yhoyhoj** [Tobi823/ffupdater#8]
Sorry, another issue.

The hash verification seems to fail for some updates. It seems that it can't hash the file correctly.
After the download the app prints an error message :
> **Download is NOT verified**
> The SHA256 hash for the file should have been:
> ---hash---
> But it was:
> ---blank---
> Either a hacker has replaced the correct download with an altered download or...

(translated from another language)
There is no value for what I think should be the calculated hash.
It happened for Firefox Preview 4.00 as well as Firefox 68.8.1

Version of the app: 68.2 (f-droid)
Android version: 9 (LineageOS 16.0)

**Comment by Tobi823** [comment]
Maybe the bug is already fixed in the latest pre-release builds. 

Can you verify that by uninstalling the old app and install the latest pre-release build from https://notabug.org/Tobiwan/ffupdater/releases? Direct link: https://notabug.org/attachments/dead4087-eddf-4115-9e74-bd98221b72e2

**Comment by yhoyhoj** [comment]
Cannot reproduce in 68.3.6. I'm closing the ticket.
Thanks for your work on this app !
