### ISSUE TITLE
Small update in the README.md section FAQ

### ISSUE THREAD

**Issue by Nickoriginal** [Tobi823/ffupdater#82]
> Tor Browser / Orbot: I will not support them because they can be installed with F-Droid. (Go to Settings > Repositories > Enable "Guardian Project Archive".)

Guardian Project Archive repo is not intended to download the latest Tor Browser and Orbot releases, they are available in the Guardian Project Official Releases repo.
https://guardianproject.info/fdroid/repo

**Comment by Tobi823** [comment]
You're right. Small slip-up on my part.
