### ISSUE TITLE
Crah report for brave

### ISSUE THREAD

**Issue by mmlg620** [Tobi823/ffupdater#86]
kotlinx.coroutines.JobCancellationException
-
Job was cancelled
-
kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@631e59a

**Comment by Tobi823** [comment]
Unfortunately, the error description does not help me. 

But I have a suspicion where and how the error occurred and how I can fix it. 

I will publish the fix in the next version.

**Comment by Tobi823** [comment]
The update is now released. You can either wait for the official F-Droid release, install the APK file from GitHub/GitLab or try my personal F-Droid repository (see https://github.com/Tobi823/ffupdater#f-droid-repository).

**Comment by mmlg620** [comment]
Hey,

all is perfect now with brave !

Thancks
