### ISSUE TITLE
Improve internet check when using AdguardForAndroid

### ISSUE THREAD

**Issue by Tobi823** [Tobi823/ffupdater#87]
can you tell me again exactly what problems you have with FFUpdater and AdguardForAndroid? 
Is there always an error thrown when you activate flight mode?

@TPS

**Comment by TPS** [comment]
As a data point, I _don't_ experience #89 in this release, while waiting for the fix for _that_ to land on F-Droid.

**Comment by Tobi823** [comment]
74.5.0 contains the real fix.

You can either wait for the official F-Droid release, install the APK file from GitHub/GitLab or try my personal F-Droid repository (see https://github.com/Tobi823/ffupdater#f-droid-repository).

**Comment by Tobi823** [comment]
I'm closing this issue because it should be fix. 

Can you give feedback if this is working for you now?

**Comment by TPS** [comment]
Sorry, took me a while to get this installed. (Your repo https://raw.githubusercontent.com/Tobi823/ffupdaterrepo/master/fdroid/repo kept giving error.)  It _does_ work for this symptom now.  I'd like to wait to see how it handles a binary release.

**Comment by Tobi823** [comment]
The official F-Droid Android client sometimes has problems accessing the APK file from my F-Droid repository.
But other clients like "Foxy Droid" work fine.

I don't know the reason for this. I guess that the official F-Droid
client has an internal cache and therefore needs more time before it can access a new version from my
repository.

**Comment by Tobi823** [comment]
>  It does work for this symptom now

:partying_face: 

> I'd like to wait to see how it handles a binary release.

I don't understand. What do you mean with "binary" release? Do you want to verify, that FFUpdater works, when a new Firefox update is available?

**Comment by TPS** [comment]
> I don't understand. What do you mean with "binary" release? Do you want to verify, that FFUpdater works, when a new Firefox update is available?

I think you've filtered out, e.g., binary beta releases from https://github.com/mozilla-mobile/focus-android/releases/ (though *I*'d rather keep those, I understand that may not be what others expect).  All I mean is that I'd like to verify how a _non-beta_ binary release is handled (whenever Mozilla gets to it) before I'm sure this is completely fine.

**Comment by Tobi823** [comment]
ah ok - now I understand.

> I think you've filtered out, e.g., binary beta releases from

Yes, FFUpdater will ignore the beta releases because most users only want the "real"/"main" releases.

>  All I mean is that I'd like to verify how a non-beta binary release is handled (whenever Mozilla gets to it) before I'm sure this is completely fine.

:+1:

**Comment by TPS** [comment]
I can finally report that this working as intended. Just now, I got v95.1.0 updated perfectly. 🙇🏾‍♂️

Sorry for the delay! 😅  Ff puts out very few actual non-beta releases (maybe 1 a month?) for this, & sometimes other app managers would update this before FFU.

**Comment by TPS** [comment]
Since most recent AG update (v4.0n31), this problem has recurred on _all_ my devices — 32- & 64-bit.

**Comment by Tobi823** [comment]
I am very busy right now because of the university. I'll look at the problem in the middle of next month.

**Comment by TPS** [comment]
> I am very busy right now because of the university.

@Tobi823 I'm in no rush. If I find more details, I'll post them, but don't feel pressured. 🙇🏾‍♂️  Do well in your studies 👨‍💻 & good luck 👨‍🎓.

**Comment by Tobi823** [comment]
Will be fixed in 75.2.0
