### ISSUE TITLE
Use UPDATE_PACKAGES_WITHOUT_USER_ACTION for automatic background app updates

### ISSUE THREAD

**Issue by Victor239** [Tobi823/ffupdater#88]
[This post](https://www.xda-developers.com/android-12-alternative-app-stores-update-apps-background/) describes how apps are now able to update themselves automatically in the background without prompting the user. This would be preferable than having to be prompted each time to update the browsers.

**Comment by dznsm** [comment]
Updating works nicely after tapping on update in the notification with no other interaction on GrapheneOS (Android 12) first place I've seen this implemented. Nice work. 
Would be real nice to have the updates apply automatically without having to tap update on the notification, I guess give a notification after the update.

**Comment by Donkey-Doug** [comment]
> updates apply automatically without having to tap update on the notification, I guess give a notification after the update.

Or something like "VLC got updated - See changelog" and pressing the notification opens the changelog.

**Comment by Tobi823** [comment]
The silent background update feature is now implemented and will be part of the next release.
