### ISSUE TITLE
Firefox Beta 94.0.0 installed instead of stable

### ISSUE THREAD

**Issue by IZ2QDH** [Tobi823/ffupdater#89]
FFupdater version 74.4.5
It notifies me to update Firefox Focus to version 94.0.0 but when APK is downloaded and installation prompt is displayed i see that the Beta version o Firefox Focus has been downloaded.

**Comment by Tobi823** [comment]
I forgot that on https://github.com/mozilla-mobile/focus-android/releases they also publish the beta versions.
