### ISSUE TITLE
Correct the description of Firefox Focus/Klar

### ISSUE THREAD

**Issue by cosify** [Tobi823/ffupdater#91]
Thanks for the great updater. 

In the app's description of Firefox Focus and Firefox Klar ( https://github.com/Tobi823/ffupdater/blob/fc5170c39f9208a67336d827331ef9b44331d661/ffupdater/src/main/res/values/strings.xml ), it states the two apps are identical, and that "_only the name is different_". 

This is incorrect. As per [Mozilla's own description](https://support.mozilla.org/en-US/kb/send-usage-data-firefox-mobile-browsers#w_why-do-you-enable-data-collection-by-default), Firefox Focus contains telemetry, enabled by default, which sends technical and interaction data back to Mozilla, as well as sending sending crash and error data to Google Firebase.

Firefox Klar has telemetry disabled by default, and even if the user manually enables it, it will only send technical and interaction data to Mozilla, without sending any data to Google. This is an important difference for any privacy-conscious user. Per Mozilla's website: "**_Data collection is turned off by default in Firefox Klar. If you enable it, we will only receive the technical and interaction data described above._** "

Could we update the apps description in strings.xml to something like "_Firefox Klar is developed for Germany, Austria and Switzerland, but can be used by users in any country. It is very similar to Firefox Focus, but the name was changed in German-speaking countries to avoid confusion with the magazine Focus by Hubert Burda Media group. Unlike Firefox Focus, Firefox Klar has telemetry disabled by default due to strict German privacy laws._"

**Comment by Tobi823** [comment]
> This is incorrect. As per Mozilla's own description, Firefox Focus contains telemetry, enabled by default, which sends technical and interaction data back to Mozilla, as well as sending sending crash and error data to Google Firebase.

I did not know that yet.

Thanks for this info and your 'pull request'. I'll update the Firefox Klar description in the next release.

> default due to strict German privacy laws.

I know if it is 100% correct. Since 2018, the German law should be harmonized with the European "General Data Protection Regulation". But it is also not so important whether it is now because of a German or European law.
