### ISSUE TITLE
Why did you added Vivaldi?

### ISSUE THREAD

**Issue by gnuhead-chieb** [Tobi823/ffupdater#92]
Vivaldi is proprietary browser.Sourcecode they provide is incomplete.

See here:https://vivaldi.com/blog/vivaldi-browser-open-source/

It should notice it to users.

**Comment by Tobi823** [comment]
> Why did you added Vivaldi?

I was asked on https://notabug.org/Tobiwan/ffupdater/issues/89 if I could add the Vivaldi browser.

FFUpdater should be an _Updater for privacy friendly browser_ - and the Vivaldi browsers seems to be one. They claim that they do not track their users and that they have some sort of tracker blocker built in. https://vivaldi.com/zerotracking/ https://vivaldi.com/privacy/

I actively follow IT news and Vivaldi has not attracted any negative attention as far as I know.

> Vivaldi is proprietary browser.Sourcecode they provide is incomplete.

I did not know this. During my research I stumbled across https://vivaldi.com/source/ and assumed that the entire source code is offered there.

Thanks for the info :+1: 

> It should notice it to users.

Yes they should. I will update the warning for Vivaldi to:

> Vivaldi is only partially open source (see https://vivaldi.com/blog/vivaldi-browser-open-source/ for more info). It also uses the technical foundation of the Google Chrome (Chromium). 
>
> Some people don't like this. Do you want to install Vivaldi?

(btw - I used _Some people don't like this_ to explain non technical people why these properties are problematic)
