### ISSUE TITLE
Shows "update" for browsers despite newer version being installed.

### ISSUE THREAD

**Issue by kyoforkshomebrews** [Tobi823/ffupdater#98]

**Comment by TPS** [comment]
I'm having the same issue w/ Ff Klar:
![FfU Main Screen.png](https://user-images.githubusercontent.com/185902/147369858-831dcfed-66dc-4581-ae1c-0d2ce6d02507.png)
![FfU D&I Detail.png](https://user-images.githubusercontent.com/185902/147369867-2daeb7ed-e590-4631-a1c3-a2133d35e822.png)

**Comment by Tobi823** [comment]
Not really a bug of FFUpdater. It seems that the maintainer of Firefox Klar published version 95.2.0, you installed it and they removed 95.2.0 from GitHub.

You have to wait until they release 96.0.0 (https://github.com/mozilla-mobile/focus-android/releases).
But you can disable the background update check for Firefox Klar until they do it.

**Comment by Tobi823** [comment]
Maybe I can improve the version comparison :thinking:

**Comment by Tobi823** [comment]
The version comparison is now improved. With the new version, this error should never occurs again.

**Comment by Tobi823** [comment]
Should be fixed in version 75.0.0

**Comment by TPS** [comment]
I don't see it in /Releases.  Is the binary still pending?

**Comment by Tobi823** [comment]
Oops. I have forgotten to upload the APK to GitHub. Here it is now: https://github.com/Tobi823/ffupdater/releases/tag/75.0.0

**Comment by TPS** [comment]
@Tobi823 That worked.  I suppose you could replace the <kbd>Fixed but not released</kbd> tag?

**Comment by Tobi823** [comment]
thanks for the hint
